-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libsignal_protocol]: type definitions
import Aeneas
import PQXDH.Aeneas.Full.Extracted.Protocol.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.longLine false
set_option linter.style.setOption false
set_option linter.style.whitespace false
set_option linter.style.nameCheck false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace libsignal_protocol

/-- [core::marker::PhantomData]
    Source: '/rustc/library/core/src/marker.rs', lines 811:0-811:39
    Name pattern: [core::marker::PhantomData]
    Visibility: public -/
@[reducible, rust_type "core::marker::PhantomData"]
def core.marker.PhantomData (T : Type) := Unit

/-- [core::ops::range::RangeFull]
    Source: '/rustc/library/core/src/ops/range.rs', lines 44:0-44:20
    Name pattern: [core::ops::range::RangeFull]
    Visibility: public -/
@[reducible, rust_type "core::ops::range::RangeFull"]
def core.ops.range.RangeFull := Unit

/-- Trait declaration: [bytes::buf::buf_impl::Buf]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bytes-1.11.1/src/buf/buf_impl.rs', lines 117:0-117:13
    Name pattern: [bytes::buf::buf_impl::Buf]
    Visibility: public -/
@[rust_trait "bytes::buf::buf_impl::Buf"]
structure bytes.buf.buf_impl.Buf (Self : Type) where
  remaining : Self → Result Std.Usize
  chunk : Self → Result (Slice Std.U8)
  advance : Self → Std.Usize → Result Self

/-- Trait declaration: [bytes::buf::buf_mut::BufMut]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bytes-1.11.1/src/buf/buf_mut.rs', lines 30:0-30:23
    Name pattern: [bytes::buf::buf_mut::BufMut]
    Visibility: public -/
@[rust_trait "bytes::buf::buf_mut::BufMut"]
structure bytes.buf.buf_mut.BufMut (Self : Type) where
  remaining_mut : Self → Result Std.Usize
  advance_mut : Self → Std.Usize → Result Self
  chunk_mut : Self → Result (bytes.buf.uninit_slice.UninitSlice ×
    (bytes.buf.uninit_slice.UninitSlice → Self))

-- derive_more...TryFromReprError: shared root def in PQXDH.Aeneas.Full.Extracted.Shared.DeriveMore.

-- libsignal_core.address.ServiceId: from PQXDH.Aeneas.Full.Extracted.Core.

-- libsignal_core.curve.KeyType: from PQXDH.Aeneas.Full.Extracted.Core.

-- libsignal_core.curve.CurveError: from PQXDH.Aeneas.Full.Extracted.Core.

-- rand_core_1.RngCore: shared root def in PQXDH.Aeneas.Full.Extracted.Shared.RandCore.

-- rand_core_1.CryptoRng: shared root def in PQXDH.Aeneas.Full.Extracted.Shared.RandCore.

-- rand.rng.Rng: shared root def in PQXDH.Aeneas.Full.Extracted.Shared.Rand.

-- libsignal_core.curve.KeyPair: from PQXDH.Aeneas.Full.Extracted.Core.

/-- [rand_core#1::UnwrapErr]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.9.3/src/lib.rs', lines 298:0-298:35
    Name pattern: [rand_core#1::UnwrapErr]
    Visibility: public -/
@[reducible, rust_type "rand_core#1::UnwrapErr"]
def rand_core_1.UnwrapErr (R : Type) (Clause0_Error : Type) := R

/-- Trait declaration: [rand_core#1::TryRngCore]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.9.3/src/lib.rs', lines 220:0-220:20
    Name pattern: [rand_core#1::TryRngCore]
    Visibility: public -/
@[rust_trait "rand_core#1::TryRngCore"
  (parentClauses := ["corefmtDebugInst", "corefmtDisplayInst"])]
structure rand_core_1.TryRngCore (Self : Type) (Self_Error : Type) where
  corefmtDebugInst : core.fmt.Debug Self_Error
  corefmtDisplayInst : core.fmt.Display Self_Error
  try_next_u32 : Self → Result ((core.result.Result Std.U32 Self_Error) ×
    Self)
  try_next_u64 : Self → Result ((core.result.Result Std.U64 Self_Error) ×
    Self)
  try_fill_bytes : Self → Slice Std.U8 → Result ((core.result.Result Unit
    Self_Error) × Self × (Slice Std.U8))
  unwrap_err : Self → Result (rand_core_1.UnwrapErr Self Self_Error)

/-- Trait declaration: [rand_core#1::TryCryptoRng]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.9.3/src/lib.rs', lines 291:0-291:34
    Name pattern: [rand_core#1::TryCryptoRng]
    Visibility: public -/
@[rust_trait "rand_core#1::TryCryptoRng" (parentClauses := ["TryRngCoreInst"])]
structure rand_core_1.TryCryptoRng (Self : Type) (Self_Clause0_Error : Type)
  where
  TryRngCoreInst : rand_core_1.TryRngCore Self Self_Clause0_Error

/-- [rand_core#1::os::OsRng]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.9.3/src/os.rs', lines 47:0-47:16
    Name pattern: [rand_core#1::os::OsRng]
    Visibility: public -/
@[reducible, rust_type "rand_core#1::os::OsRng"]
def rand_core_1.os.OsRng := Unit

/-- [spqr::chain::ChainParams]
    Source: '/cargo/git/checkouts/sparsepostquantumratchet-b58d7f56e3645ccd/f2589fe/src/chain.rs', lines 17:0-17:22
    Name pattern: [spqr::chain::ChainParams]
    Visibility: public -/
@[rust_type "spqr::chain::ChainParams"]
structure spqr.chain.ChainParams where
  max_jump : Std.U32
  max_ooo_keys : Std.U32

/-- [spqr::encoding::polynomial::PolynomialError]
    Source: '/cargo/git/checkouts/sparsepostquantumratchet-b58d7f56e3645ccd/f2589fe/src/encoding/polynomial.rs', lines 13:0-13:24
    Name pattern: [spqr::encoding::polynomial::PolynomialError]
    Visibility: public -/
@[discriminant isize, rust_type "spqr::encoding::polynomial::PolynomialError"]
inductive spqr.encoding.polynomial.PolynomialError where
| MessageLengthEven : spqr.encoding.polynomial.PolynomialError
| MessageLengthTooLong : spqr.encoding.polynomial.PolynomialError
| SerializationInvalid : spqr.encoding.polynomial.PolynomialError

/-- [spqr::encoding::EncodingError]
    Source: '/cargo/git/checkouts/sparsepostquantumratchet-b58d7f56e3645ccd/f2589fe/src/encoding.rs', lines 9:0-9:22
    Name pattern: [spqr::encoding::EncodingError]
    Visibility: public -/
@[discriminant isize, rust_type "spqr::encoding::EncodingError"]
inductive spqr.encoding.EncodingError where
| PolynomialError :
  spqr.encoding.polynomial.PolynomialError →
  spqr.encoding.EncodingError
| ChunkIndexDecodingError : spqr.encoding.EncodingError
| ChunkDataDecodingError : spqr.encoding.EncodingError

/-- [spqr::proto::pq_ratchet::Direction]
    Source: 'target/out/signal.proto.pq_ratchet.rs', lines 402:0-402:18
    Name pattern: [spqr::proto::pq_ratchet::Direction]
    Visibility: public -/
@[discriminant i32, rust_type "spqr::proto::pq_ratchet::Direction"]
inductive spqr.proto.pq_ratchet.Direction where
| A2B : spqr.proto.pq_ratchet.Direction
| B2A : spqr.proto.pq_ratchet.Direction

/-- [spqr::proto::pq_ratchet::Version]
    Source: 'target/out/signal.proto.pq_ratchet.rs', lines 375:0-375:16
    Name pattern: [spqr::proto::pq_ratchet::Version]
    Visibility: public -/
@[discriminant i32, rust_type "spqr::proto::pq_ratchet::Version"]
inductive spqr.proto.pq_ratchet.Version where
| V0 : spqr.proto.pq_ratchet.Version
| V1 : spqr.proto.pq_ratchet.Version

/-- [spqr::Params]
    Source: '/cargo/git/checkouts/sparsepostquantumratchet-b58d7f56e3645ccd/f2589fe/src/lib.rs', lines 54:0-54:21
    Name pattern: [spqr::Params]
    Visibility: public -/
@[rust_type "spqr::Params"]
structure spqr.Params where
  direction : spqr.proto.pq_ratchet.Direction
  version : spqr.proto.pq_ratchet.Version
  min_version : spqr.proto.pq_ratchet.Version
  auth_key : Slice Std.U8
  chain_params : spqr.chain.ChainParams

/-- [spqr::serialize::Error]
    Source: '/cargo/git/checkouts/sparsepostquantumratchet-b58d7f56e3645ccd/f2589fe/src/serialize.rs', lines 7:0-7:14
    Name pattern: [spqr::serialize::Error]
    Visibility: public -/
@[discriminant isize, rust_type "spqr::serialize::Error"]
inductive spqr.serialize.Error where
| Deserialization : spqr.serialize.Error
| EncodingDecoding : spqr.serialize.Error

/-- [spqr::Error]
    Source: '/cargo/git/checkouts/sparsepostquantumratchet-b58d7f56e3645ccd/f2589fe/src/lib.rs', lines 96:0-96:14
    Name pattern: [spqr::Error]
    Visibility: public -/
@[discriminant isize, rust_type "spqr::Error"]
inductive spqr.Error where
| StateDecode : spqr.Error
| NotImplemented : spqr.Error
| MsgDecode : spqr.Error
| MacVerifyFailed : spqr.Error
| EpochOutOfRange : Std.U64 → spqr.Error
| EncodingDecoding : spqr.encoding.EncodingError → spqr.Error
| Serialization : spqr.serialize.Error → spqr.Error
| VersionMismatch : spqr.Error
| MinimumVersion : spqr.Error
| KeyJump : Std.U32 → Std.U32 → spqr.Error
| KeyTrimmed : Std.U32 → spqr.Error
| KeyAlreadyRequested : Std.U32 → spqr.Error
| ErroneousDataReceived : spqr.Error
| SendKeyEpochDecreased : Std.U64 → Std.U64 → spqr.Error
| InvalidParams : Str → spqr.Error
| ChainNotAvailable : spqr.Error

/-- [libsignal_protocol::proto::fingerprint::LogicalFingerprint]
    Source: 'target/out/signal.proto.fingerprint.rs', lines 3:0-7:1
    Visibility: public -/
structure proto.fingerprint.LogicalFingerprint where
  content : Option (alloc.vec.Vec Std.U8)

/-- [libsignal_protocol::proto::fingerprint::CombinedFingerprints]
    Source: 'target/out/signal.proto.fingerprint.rs', lines 9:0-16:1
    Visibility: public -/
structure proto.fingerprint.CombinedFingerprints where
  version : Option Std.U32
  local_fingerprint : Option proto.fingerprint.LogicalFingerprint
  remote_fingerprint : Option proto.fingerprint.LogicalFingerprint

/-- [libsignal_protocol::proto::storage::session_structure::PendingKyberPreKey]
    Source: 'target/out/signal.proto.storage.rs', lines 85:4-90:5
    Visibility: public -/
structure proto.storage.session_structure.PendingKyberPreKey where
  pre_key_id : Std.U32
  ciphertext : alloc.vec.Vec Std.U8

/-- [libsignal_protocol::proto::storage::session_structure::PendingPreKey]
    Source: 'target/out/signal.proto.storage.rs', lines 74:4-83:5
    Visibility: public -/
structure proto.storage.session_structure.PendingPreKey where
  pre_key_id : Option Std.U32
  signed_pre_key_id : Std.I32
  base_key : alloc.vec.Vec Std.U8
  timestamp : Std.U64

/-- [libsignal_protocol::proto::storage::session_structure::chain::MessageKey]
    Source: 'target/out/signal.proto.storage.rs', lines 58:8-71:9
    Visibility: public -/
structure proto.storage.session_structure.chain.MessageKey where
  index : Std.U32
  cipher_key : alloc.vec.Vec Std.U8
  mac_key : alloc.vec.Vec Std.U8
  iv : alloc.vec.Vec Std.U8
  seed : alloc.vec.Vec Std.U8

/-- [libsignal_protocol::proto::storage::session_structure::chain::ChainKey]
    Source: 'target/out/signal.proto.storage.rs', lines 51:8-56:9
    Visibility: public -/
structure proto.storage.session_structure.chain.ChainKey where
  index : Std.U32
  key : alloc.vec.Vec Std.U8

/-- [libsignal_protocol::proto::storage::session_structure::Chain]
    Source: 'target/out/signal.proto.storage.rs', lines 38:4-47:5
    Visibility: public -/
structure proto.storage.session_structure.Chain where
  sender_ratchet_key : alloc.vec.Vec Std.U8
  sender_ratchet_key_private : alloc.vec.Vec Std.U8
  chain_key : Option proto.storage.session_structure.chain.ChainKey
  message_keys : alloc.vec.Vec proto.storage.session_structure.chain.MessageKey

/-- [libsignal_protocol::proto::storage::SessionStructure]
    Source: 'target/out/signal.proto.storage.rs', lines 3:0-34:1
    Visibility: public -/
structure proto.storage.SessionStructure where
  session_version : Std.U32
  local_identity_public : alloc.vec.Vec Std.U8
  remote_identity_public : alloc.vec.Vec Std.U8
  root_key : alloc.vec.Vec Std.U8
  previous_counter : Std.U32
  sender_chain : Option proto.storage.session_structure.Chain
  receiver_chains : alloc.vec.Vec proto.storage.session_structure.Chain
  pending_pre_key : Option proto.storage.session_structure.PendingPreKey
  pending_kyber_pre_key : Option
    proto.storage.session_structure.PendingKyberPreKey
  remote_registration_id : Std.U32
  local_registration_id : Std.U32
  alice_base_key : alloc.vec.Vec Std.U8
  pq_ratchet_state : alloc.vec.Vec Std.U8

/-- [libsignal_protocol::proto::storage::RecordStructure]
    Source: 'target/out/signal.proto.storage.rs', lines 93:0-99:1
    Visibility: public -/
structure proto.storage.RecordStructure where
  current_session : Option proto.storage.SessionStructure
  previous_sessions : alloc.vec.Vec (alloc.vec.Vec Std.U8)

/-- [libsignal_protocol::proto::storage::PreKeyRecordStructure]
    Source: 'target/out/signal.proto.storage.rs', lines 101:0-108:1
    Visibility: public -/
structure proto.storage.PreKeyRecordStructure where
  id : Std.U32
  public_key : alloc.vec.Vec Std.U8
  private_key : alloc.vec.Vec Std.U8

/-- [libsignal_protocol::proto::storage::SignedPreKeyRecordStructure]
    Source: 'target/out/signal.proto.storage.rs', lines 110:0-121:1
    Visibility: public -/
structure proto.storage.SignedPreKeyRecordStructure where
  id : Std.U32
  public_key : alloc.vec.Vec Std.U8
  private_key : alloc.vec.Vec Std.U8
  signature : alloc.vec.Vec Std.U8
  timestamp : Std.U64

/-- [libsignal_protocol::proto::storage::IdentityKeyPairStructure]
    Source: 'target/out/signal.proto.storage.rs', lines 123:0-128:1
    Visibility: public -/
structure proto.storage.IdentityKeyPairStructure where
  public_key : alloc.vec.Vec Std.U8
  private_key : alloc.vec.Vec Std.U8

/-- [libsignal_protocol::proto::storage::sender_key_state_structure::SenderSigningKey]
    Source: 'target/out/signal.proto.storage.rs', lines 165:4-170:5
    Visibility: public -/
structure proto.storage.sender_key_state_structure.SenderSigningKey where
  «public» : alloc.vec.Vec Std.U8
  «private» : alloc.vec.Vec Std.U8

/-- [libsignal_protocol::proto::storage::sender_key_state_structure::SenderMessageKey]
    Source: 'target/out/signal.proto.storage.rs', lines 158:4-163:5
    Visibility: public -/
structure proto.storage.sender_key_state_structure.SenderMessageKey where
  iteration : Std.U32
  seed : alloc.vec.Vec Std.U8

/-- [libsignal_protocol::proto::storage::sender_key_state_structure::SenderChainKey]
    Source: 'target/out/signal.proto.storage.rs', lines 151:4-156:5
    Visibility: public -/
structure proto.storage.sender_key_state_structure.SenderChainKey where
  iteration : Std.U32
  seed : alloc.vec.Vec Std.U8

/-- [libsignal_protocol::proto::storage::SenderKeyStateStructure]
    Source: 'target/out/signal.proto.storage.rs', lines 130:0-147:1
    Visibility: public -/
structure proto.storage.SenderKeyStateStructure where
  message_version : Std.U32
  chain_id : Std.U32
  sender_chain_key : Option
    proto.storage.sender_key_state_structure.SenderChainKey
  sender_signing_key : Option
    proto.storage.sender_key_state_structure.SenderSigningKey
  sender_message_keys : alloc.vec.Vec
    proto.storage.sender_key_state_structure.SenderMessageKey

/-- [libsignal_protocol::proto::storage::SenderKeyRecordStructure]
    Source: 'target/out/signal.proto.storage.rs', lines 173:0-176:1
    Visibility: public -/
structure proto.storage.SenderKeyRecordStructure where
  sender_key_states : alloc.vec.Vec proto.storage.SenderKeyStateStructure

/-- [libsignal_protocol::proto::wire::SignalMessage]
    Source: 'target/out/signal.proto.wire.rs', lines 3:0-16:1
    Visibility: public -/
structure proto.wire.SignalMessage where
  ratchet_key : Option (alloc.vec.Vec Std.U8)
  counter : Option Std.U32
  previous_counter : Option Std.U32
  ciphertext : Option (alloc.vec.Vec Std.U8)
  pq_ratchet : Option (alloc.vec.Vec Std.U8)
  addresses : Option (alloc.vec.Vec Std.U8)

/-- [libsignal_protocol::proto::wire::PreKeySignalMessage]
    Source: 'target/out/signal.proto.wire.rs', lines 18:0-36:1
    Visibility: public -/
structure proto.wire.PreKeySignalMessage where
  registration_id : Option Std.U32
  pre_key_id : Option Std.U32
  signed_pre_key_id : Option Std.U32
  kyber_pre_key_id : Option Std.U32
  kyber_ciphertext : Option (alloc.vec.Vec Std.U8)
  base_key : Option (alloc.vec.Vec Std.U8)
  identity_key : Option (alloc.vec.Vec Std.U8)
  message : Option (alloc.vec.Vec Std.U8)

/-- [libsignal_protocol::proto::wire::SenderKeyMessage]
    Source: 'target/out/signal.proto.wire.rs', lines 38:0-47:1
    Visibility: public -/
structure proto.wire.SenderKeyMessage where
  distribution_uuid : Option (alloc.vec.Vec Std.U8)
  chain_id : Option Std.U32
  iteration : Option Std.U32
  ciphertext : Option (alloc.vec.Vec Std.U8)

/-- [libsignal_protocol::proto::wire::SenderKeyDistributionMessage]
    Source: 'target/out/signal.proto.wire.rs', lines 49:0-60:1
    Visibility: public -/
structure proto.wire.SenderKeyDistributionMessage where
  distribution_uuid : Option (alloc.vec.Vec Std.U8)
  chain_id : Option Std.U32
  iteration : Option Std.U32
  chain_key : Option (alloc.vec.Vec Std.U8)
  signing_key : Option (alloc.vec.Vec Std.U8)

/-- [libsignal_protocol::proto::service::DecryptionErrorMessage]
    Source: 'target/out/signalservice.rs', lines 24:0-32:1
    Visibility: public -/
structure proto.service.DecryptionErrorMessage where
  ratchet_key : Option (alloc.vec.Vec Std.U8)
  timestamp : Option Std.U64
  device_id : Option Std.U32

/-- [libsignal_protocol::crypto::EncryptionError]
    Source: 'rust/protocol/src/crypto.rs', lines 15:0-18:1 -/
@[discriminant isize]
inductive crypto.EncryptionError where
| BadKeyOrIv : crypto.EncryptionError

/-- [libsignal_protocol::crypto::DecryptionError]
    Source: 'rust/protocol/src/crypto.rs', lines 21:0-28:1 -/
@[discriminant isize]
inductive crypto.DecryptionError where
| BadKeyOrIv : crypto.DecryptionError
| BadCiphertext : Str → crypto.DecryptionError

/-- [libsignal_protocol::crypto::aes_256_ctr_decrypt::closure]
    Source: 'rust/protocol/src/crypto.rs', lines 43:44-45:5 -/
@[reducible]
def crypto.aes_256_ctr_decrypt.closure := Unit

/-- [libsignal_protocol::ratchet::keys::RootKey]
    Source: 'rust/protocol/src/ratchet/keys.rs', lines 186:0-188:1 -/
structure ratchet.keys.RootKey where
  key : Array Std.U8 32#usize

/-- [libsignal_protocol::ratchet::keys::ChainKey]
    Source: 'rust/protocol/src/ratchet/keys.rs', lines 142:0-145:1 -/
structure ratchet.keys.ChainKey where
  key : Array Std.U8 32#usize
  index : Std.U32

/-- [libsignal_protocol::double_ratchet::SenderChain]
    Source: 'rust/protocol/src/double_ratchet.rs', lines 47:0-50:1 -/
structure double_ratchet.SenderChain where
  ratchet_key : libsignal_core.curve.KeyPair
  chain_key : ratchet.keys.ChainKey

/-- [libsignal_protocol::double_ratchet::RatchetState]
    Source: 'rust/protocol/src/double_ratchet.rs', lines 32:0-42:1 -/
structure double_ratchet.RatchetState where
  root_key : ratchet.keys.RootKey
  sender_chain : Option double_ratchet.SenderChain
  receiver_chains : alloc.vec.Vec proto.storage.session_structure.Chain
  previous_counter : Std.U32
  max_forward_jumps : Std.Usize

/-- [libsignal_protocol::state::session::InvalidSessionError]
    Source: 'rust/protocol/src/state/session.rs', lines 27:0-27:63 -/
@[reducible]
def state.session.InvalidSessionError := Str

/-- [libsignal_protocol::protocol::CiphertextMessageType]
    Source: 'rust/protocol/src/protocol.rs', lines 35:0-40:1
    Visibility: public -/
@[discriminant u8 [2,3,7,8]]
inductive protocol.CiphertextMessageType where
| Whisper : protocol.CiphertextMessageType
| PreKey : protocol.CiphertextMessageType
| SenderKey : protocol.CiphertextMessageType
| Plaintext : protocol.CiphertextMessageType

/-- [libsignal_protocol::kem::KeyType]
    Source: 'rust/protocol/src/kem.rs', lines 203:0-212:1
    Visibility: public -/
@[discriminant isize]
inductive kem.KeyType where
| Kyber1024 : kem.KeyType

/-- [libsignal_protocol::error::SessionNotFound]
    Source: 'rust/protocol/src/error.rs', lines 111:0-114:1
    Visibility: public -/
structure error.SessionNotFound where
  address : Option libsignal_core.address.ProtocolAddress
  op : Str

/-- [libsignal_protocol::error::SignalProtocolError]
    Source: 'rust/protocol/src/error.rs', lines 19:0-108:1
    Visibility: public -/
@[discriminant isize]
inductive error.SignalProtocolError where
| InvalidArgument : String → error.SignalProtocolError
| InvalidState : Str → String → error.SignalProtocolError
| InvalidProtobufEncoding : error.SignalProtocolError
| CiphertextMessageTooShort : Std.Usize → error.SignalProtocolError
| LegacyCiphertextVersion : Std.U8 → error.SignalProtocolError
| UnrecognizedCiphertextVersion : Std.U8 → error.SignalProtocolError
| UnrecognizedMessageVersion : Std.U32 → error.SignalProtocolError
| NoKeyTypeIdentifier : error.SignalProtocolError
| BadKeyType : Std.U8 → error.SignalProtocolError
| BadKeyLength :
  libsignal_core.curve.KeyType →
  Std.Usize →
  error.SignalProtocolError
| InvalidKeyAgreement : error.SignalProtocolError
| SignatureValidationFailed : error.SignalProtocolError
| UntrustedIdentity :
  libsignal_core.address.ProtocolAddress →
  error.SignalProtocolError
| InvalidPreKeyId : error.SignalProtocolError
| InvalidSignedPreKeyId : error.SignalProtocolError
| InvalidKyberPreKeyId : error.SignalProtocolError
| InvalidMacKeyLength : Std.Usize → error.SignalProtocolError
| NoSenderKeyState : uuid.Uuid → error.SignalProtocolError
| InvalidProtocolAddress : String → Std.U32 → error.SignalProtocolError
| SessionNotFound : error.SessionNotFound → error.SignalProtocolError
| InvalidSessionStructure : Str → error.SignalProtocolError
| InvalidSenderKeySession : uuid.Uuid → error.SignalProtocolError
| InvalidRegistrationId :
  libsignal_core.address.ProtocolAddress →
  Std.U32 →
  error.SignalProtocolError
| DuplicatedMessage : Std.U32 → Std.U32 → error.SignalProtocolError
| InvalidMessage :
  protocol.CiphertextMessageType →
  String →
  error.SignalProtocolError
| FfiBindingError : String → error.SignalProtocolError
| InvalidSealedSenderMessage : String → error.SignalProtocolError
| UnknownSealedSenderVersion : Std.U8 → error.SignalProtocolError
| SealedSenderSelfSend : error.SignalProtocolError
| UnknownSealedSenderServerCertificateId :
  Std.U32 →
  error.SignalProtocolError
| BadKEMKeyType : Std.U8 → error.SignalProtocolError
| WrongKEMKeyType : Std.U8 → Std.U8 → error.SignalProtocolError
| BadKEMKeyLength : kem.KeyType → Std.Usize → error.SignalProtocolError
| BadKEMCiphertextLength :
  kem.KeyType →
  Std.Usize →
  error.SignalProtocolError

/-- [libsignal_protocol::ratchet::keys::MessageKeys]
    Source: 'rust/protocol/src/ratchet/keys.rs', lines 92:0-97:1 -/
structure ratchet.keys.MessageKeys where
  cipher_key : Array Std.U8 32#usize
  mac_key : Array Std.U8 32#usize
  iv : Array Std.U8 16#usize
  counter : Std.U32

/-- [libsignal_protocol::ratchet::keys::MessageKeyGenerator]
    Source: 'rust/protocol/src/ratchet/keys.rs', lines 14:0-17:1 -/
@[discriminant isize]
inductive ratchet.keys.MessageKeyGenerator where
| Keys : ratchet.keys.MessageKeys → ratchet.keys.MessageKeyGenerator
| Seed :
  ((alloc.vec.Vec Std.U8) × Std.U32) →
  ratchet.keys.MessageKeyGenerator

/-- Trait declaration: [libsignal_protocol::fingerprint::_::DisplayToDisplayDoc]
    Source: 'rust/protocol/src/fingerprint.rs', lines 16:16-16:35 -/
structure fingerprint._.DisplayToDisplayDoc (Self : Type) where
  __displaydoc_display : Self → Result Self

/-- Trait declaration: [libsignal_protocol::fingerprint::_::PathToDisplayDoc]
    Source: 'rust/protocol/src/fingerprint.rs', lines 16:16-16:35 -/
structure fingerprint._.PathToDisplayDoc (Self : Type) where
  __displaydoc_display : Self → Result std.path.Display

/-- [libsignal_protocol::fingerprint::Error]
    Source: 'rust/protocol/src/fingerprint.rs', lines 17:0-24:1
    Visibility: public -/
@[discriminant isize]
inductive fingerprint.Error where
| VersionMismatch : Std.U32 → Std.U32 → fingerprint.Error
| ParsingError : Str → fingerprint.Error
| InvalidIterationCount : Std.U32 → fingerprint.Error

/-- [libsignal_protocol::fingerprint::DisplayableFingerprint]
    Source: 'rust/protocol/src/fingerprint.rs', lines 27:0-30:1
    Visibility: public -/
structure fingerprint.DisplayableFingerprint where
  «local» : String
  remote : String

/-- [libsignal_protocol::fingerprint::ScannableFingerprint]
    Source: 'rust/protocol/src/fingerprint.rs', lines 76:0-80:1
    Visibility: public -/
structure fingerprint.ScannableFingerprint where
  version : Std.U32
  local_fingerprint : alloc.vec.Vec Std.U8
  remote_fingerprint : alloc.vec.Vec Std.U8

/-- [libsignal_protocol::fingerprint::Fingerprint]
    Source: 'rust/protocol/src/fingerprint.rs', lines 155:0-158:1
    Visibility: public -/
structure fingerprint.Fingerprint where
  display : fingerprint.DisplayableFingerprint
  scannable : fingerprint.ScannableFingerprint

/-- [libsignal_protocol::identity_key::IdentityKey]
    Source: 'rust/protocol/src/identity_key.rs', lines 24:0-26:1
    Visibility: public -/
structure identity_key.IdentityKey where
  public_key : libsignal_core.curve.PublicKey

/-- [libsignal_protocol::identity_key::IdentityKeyPair]
    Source: 'rust/protocol/src/identity_key.rs', lines 111:0-114:1
    Visibility: public -/
structure identity_key.IdentityKeyPair where
  identity_key : identity_key.IdentityKey
  private_key : libsignal_core.curve.PrivateKey

/-- [libsignal_protocol::identity_key::{impl core::convert::TryFrom<&'_0 [u8], libsignal_protocol::error::SignalProtocolError> for libsignal_protocol::identity_key::IdentityKeyPair}::try_from::closure]
    Source: 'rust/protocol/src/identity_key.rs', lines 186:21-186:69 -/
@[reducible]
def identity_key.TryFromIdentityKeyPairShared0SliceU8SignalProtocolError.try_from.closure
  :=
Unit

/-- [libsignal_protocol::kem::KeyMaterial]
    Source: 'rust/protocol/src/kem.rs', lines 276:0-280:1 -/
structure kem.KeyMaterial (T : Type) where
  data : Slice Std.U8
  kind : core.marker.PhantomData T

/-- [libsignal_protocol::kem::Public]
    Source: 'rust/protocol/src/kem.rs', lines 258:0-258:18
    Visibility: public -/
inductive kem.Public where

/-- [libsignal_protocol::kem::BadKEMKeyLength]
    Source: 'rust/protocol/src/kem.rs', lines 193:0-193:23 -/
@[reducible]
def kem.BadKEMKeyLength := Unit

/-- [libsignal_protocol::kem::Secret]
    Source: 'rust/protocol/src/kem.rs', lines 266:0-266:18
    Visibility: public -/
inductive kem.Secret where

/-- [libsignal_protocol::kem::DecapsulateError]
    Source: 'rust/protocol/src/kem.rs', lines 196:0-199:1 -/
@[discriminant isize]
inductive kem.DecapsulateError where
| BadKeyLength : kem.DecapsulateError
| BadCiphertext : kem.DecapsulateError

/-- Trait declaration: [libsignal_protocol::kem::KeyKind]
    Source: 'rust/protocol/src/kem.rs', lines 254:0-256:1
    Visibility: public -/
structure kem.KeyKind (Self : Type) where
  key_length : kem.KeyType → Result Std.Usize

/-- [libsignal_protocol::kem::Key]
    Source: 'rust/protocol/src/kem.rs', lines 304:0-307:1
    Visibility: public -/
structure kem.Key (T : Type) where
  key_type : kem.KeyType
  key_data : kem.KeyMaterial T

/-- [libsignal_protocol::kem::Ciphertext]
    Source: 'rust/protocol/src/kem.rs', lines 501:0-504:1 -/
structure kem.Ciphertext where
  key_type : kem.KeyType
  data : Slice Std.U8

/-- [libsignal_protocol::kem::{libsignal_protocol::kem::Key<libsignal_protocol::kem::Public>}::encapsulate::closure]
    Source: 'rust/protocol/src/kem.rs', lines 362:21-364:13 -/
@[reducible]
def kem.KeyPublic.encapsulate.closure (R : Type) := kem.Key kem.Public

/-- [libsignal_protocol::kem::{libsignal_protocol::kem::Key<libsignal_protocol::kem::Secret>}::decapsulate::closure]
    Source: 'rust/protocol/src/kem.rs', lines 395:21-402:13 -/
def kem.KeySecret.decapsulate.closure := kem.Key kem.Secret × Slice Std.U8

/-- [libsignal_protocol::kem::KeyPair]
    Source: 'rust/protocol/src/kem.rs', lines 452:0-455:1
    Visibility: public -/
structure kem.KeyPair where
  public_key : kem.Key kem.Public
  secret_key : kem.Key kem.Secret

/-- [libsignal_protocol::pqxdh::Pqxdh]
    Source: 'rust/protocol/src/pqxdh.rs', lines 36:0-36:24 -/
@[reducible]
def pqxdh.Pqxdh := Unit

/-- [libsignal_protocol::pqxdh::HandshakeKeys]
    Source: 'rust/protocol/src/pqxdh.rs', lines 65:0-69:1 -/
structure pqxdh.HandshakeKeys where
  root_key : ratchet.keys.RootKey
  chain_key : ratchet.keys.ChainKey
  pqr_key : Array Std.U8 32#usize

/-- [libsignal_protocol::pqxdh::InitiatorAgreement]
    Source: 'rust/protocol/src/pqxdh.rs', lines 101:0-106:1 -/
structure pqxdh.InitiatorAgreement where
  keys : pqxdh.HandshakeKeys
  kyber_ciphertext : Slice Std.U8

/-- [libsignal_protocol::pqxdh::InitiatorParameters]
    Source: 'rust/protocol/src/pqxdh.rs', lines 113:0-124:1
    Visibility: public -/
structure pqxdh.InitiatorParameters where
  our_identity_key_pair : identity_key.IdentityKeyPair
  our_ephemeral_key_pair : libsignal_core.curve.KeyPair
  their_identity_key : identity_key.IdentityKey
  their_signed_pre_key : libsignal_core.curve.PublicKey
  their_one_time_pre_key : Option libsignal_core.curve.PublicKey
  their_ratchet_key : libsignal_core.curve.PublicKey
  their_kyber_pre_key : kem.Key kem.Public
  self_session : Bool

/-- [libsignal_protocol::pqxdh::RecipientParameters]
    Source: 'rust/protocol/src/pqxdh.rs', lines 248:0-259:1
    Visibility: public -/
structure pqxdh.RecipientParameters where
  our_identity_key_pair : identity_key.IdentityKeyPair
  our_signed_pre_key_pair : libsignal_core.curve.KeyPair
  our_one_time_pre_key_pair : Option libsignal_core.curve.KeyPair
  our_kyber_pre_key_pair : kem.KeyPair
  their_identity_key : identity_key.IdentityKey
  their_ephemeral_key : libsignal_core.curve.PublicKey
  their_kyber_ciphertext : Slice Std.U8
  self_session : Bool

/-- [libsignal_protocol::protocol::PlaintextContent]
    Source: 'rust/protocol/src/protocol.rs', lines 810:0-812:1
    Visibility: public -/
structure protocol.PlaintextContent where
  serialized : Slice Std.U8

/-- [libsignal_protocol::protocol::SenderKeyMessage]
    Source: 'rust/protocol/src/protocol.rs', lines 523:0-530:1
    Visibility: public -/
structure protocol.SenderKeyMessage where
  message_version : Std.U8
  distribution_id : uuid.Uuid
  chain_id : Std.U32
  iteration : Std.U32
  ciphertext : Slice Std.U8
  serialized : Slice Std.U8

/-- [libsignal_protocol::state::signed_prekey::SignedPreKeyId]
    Source: 'rust/protocol/src/state/signed_prekey.rs', lines 18:0-18:31
    Visibility: public -/
@[reducible]
def state.signed_prekey.SignedPreKeyId := Std.U32

/-- [libsignal_protocol::state::prekey::PreKeyId]
    Source: 'rust/protocol/src/state/prekey.rs', lines 17:0-17:25
    Visibility: public -/
@[reducible]
def state.prekey.PreKeyId := Std.U32

/-- [libsignal_protocol::state::kyber_prekey::KyberPreKeyId]
    Source: 'rust/protocol/src/state/kyber_prekey.rs', lines 18:0-18:30
    Visibility: public -/
@[reducible]
def state.kyber_prekey.KyberPreKeyId := Std.U32

/-- [libsignal_protocol::protocol::KyberPayload]
    Source: 'rust/protocol/src/protocol.rs', lines 322:0-325:1
    Visibility: public -/
structure protocol.KyberPayload where
  pre_key_id : state.kyber_prekey.KyberPreKeyId
  ciphertext : Slice Std.U8

/-- [libsignal_protocol::protocol::SignalMessage]
    Source: 'rust/protocol/src/protocol.rs', lines 63:0-73:1
    Visibility: public -/
structure protocol.SignalMessage where
  message_version : Std.U8
  sender_ratchet_key : libsignal_core.curve.PublicKey
  counter : Std.U32
  previous_counter : Std.U32
  ciphertext : Slice Std.U8
  pq_ratchet : alloc.vec.Vec Std.U8
  addresses : Option (Slice Std.U8)
  serialized : Slice Std.U8

/-- [libsignal_protocol::protocol::PreKeySignalMessage]
    Source: 'rust/protocol/src/protocol.rs', lines 337:0-349:1
    Visibility: public -/
structure protocol.PreKeySignalMessage where
  message_version : Std.U8
  registration_id : Std.U32
  pre_key_id : Option state.prekey.PreKeyId
  signed_pre_key_id : state.signed_prekey.SignedPreKeyId
  kyber_payload : Option protocol.KyberPayload
  base_key : libsignal_core.curve.PublicKey
  identity_key : identity_key.IdentityKey
  message : protocol.SignalMessage
  serialized : Slice Std.U8

/-- [libsignal_protocol::protocol::CiphertextMessage]
    Source: 'rust/protocol/src/protocol.rs', lines 25:0-30:1
    Visibility: public -/
@[discriminant isize]
inductive protocol.CiphertextMessage where
| SignalMessage : protocol.SignalMessage → protocol.CiphertextMessage
| PreKeySignalMessage :
  protocol.PreKeySignalMessage →
  protocol.CiphertextMessage
| SenderKeyMessage : protocol.SenderKeyMessage → protocol.CiphertextMessage
| PlaintextContent : protocol.PlaintextContent → protocol.CiphertextMessage

/-- [libsignal_protocol::protocol::{libsignal_protocol::protocol::SignalMessage}::new::closure]
    Source: 'rust/protocol/src/protocol.rs', lines 92:31-92:97 -/
@[reducible]
def protocol.SignalMessage.new.closure := Unit

/-- [libsignal_protocol::protocol::{libsignal_protocol::protocol::PreKeySignalMessage}::new::closure#2]
    Source: 'rust/protocol/src/protocol.rs', lines 369:21-369:54 -/
@[reducible]
def protocol.PreKeySignalMessage.new.closure_2 := Unit

/-- [libsignal_protocol::protocol::{libsignal_protocol::protocol::PreKeySignalMessage}::new::closure#1]
    Source: 'rust/protocol/src/protocol.rs', lines 366:57-366:88 -/
@[reducible]
def protocol.PreKeySignalMessage.new.closure_1 := Unit

/-- [libsignal_protocol::protocol::{libsignal_protocol::protocol::PreKeySignalMessage}::new::closure]
    Source: 'rust/protocol/src/protocol.rs', lines 364:39-364:53 -/
@[reducible]
def protocol.PreKeySignalMessage.new.closure := Unit

/-- [libsignal_protocol::protocol::{libsignal_protocol::protocol::PreKeySignalMessage}::kyber_pre_key_id::closure]
    Source: 'rust/protocol/src/protocol.rs', lines 414:40-414:64 -/
@[reducible]
def protocol.PreKeySignalMessage.kyber_pre_key_id.closure := Unit

/-- [libsignal_protocol::protocol::SenderKeyDistributionMessage]
    Source: 'rust/protocol/src/protocol.rs', lines 664:0-672:1
    Visibility: public -/
structure protocol.SenderKeyDistributionMessage where
  message_version : Std.U8
  distribution_id : uuid.Uuid
  chain_id : Std.U32
  iteration : Std.U32
  chain_key : alloc.vec.Vec Std.U8
  signing_key : libsignal_core.curve.PublicKey
  serialized : Slice Std.U8

/-- [libsignal_protocol::timestamp::Timestamp]
    Source: 'rust/protocol/src/timestamp.rs', lines 13:0-15:1
    Visibility: public -/
structure timestamp.Timestamp where
  millis : Std.U64

/-- [libsignal_protocol::protocol::DecryptionErrorMessage]
    Source: 'rust/protocol/src/protocol.rs', lines 874:0-879:1
    Visibility: public -/
structure protocol.DecryptionErrorMessage where
  ratchet_key : Option libsignal_core.curve.PublicKey
  timestamp : timestamp.Timestamp
  device_id : Std.U32
  serialized : Slice Std.U8

/-- [libsignal_protocol::protocol::{libsignal_protocol::protocol::DecryptionErrorMessage}::for_original::closure]
    Source: 'rust/protocol/src/protocol.rs', lines 907:41-907:65 -/
@[reducible]
def protocol.DecryptionErrorMessage.for_original.closure := Unit

/-- [libsignal_protocol::state::session::SessionState]
    Source: 'rust/protocol/src/state/session.rs', lines 165:0-167:1 -/
structure state.session.SessionState where
  session : proto.storage.SessionStructure

/-- [libsignal_protocol::ratchet::initialize_initiator_session::closure]
    Source: 'rust/protocol/src/ratchet.rs', lines 92:13-98:5 -/
@[reducible]
def ratchet.initialize_initiator_session.closure (R : Type) := Unit

/-- [libsignal_protocol::ratchet::initialize_recipient_session::closure]
    Source: 'rust/protocol/src/ratchet.rs', lines 155:13-161:5 -/
@[reducible]
def ratchet.initialize_recipient_session.closure := Unit

/-- [libsignal_protocol::state::session::SessionRecord]
    Source: 'rust/protocol/src/state/session.rs', lines 733:0-736:1
    Visibility: public -/
structure state.session.SessionRecord where
  current_session : Option state.session.SessionState
  previous_sessions : alloc.vec.Vec (alloc.vec.Vec Std.U8)

/-- [libsignal_protocol::sender_keys::InvalidSessionError]
    Source: 'rust/protocol/src/sender_keys.rs', lines 17:0-17:52 -/
@[reducible]
def sender_keys.InvalidSessionError := Str

/-- [libsignal_protocol::sender_keys::SenderMessageKey]
    Source: 'rust/protocol/src/sender_keys.rs', lines 26:0-31:1 -/
structure sender_keys.SenderMessageKey where
  iteration : Std.U32
  iv : alloc.vec.Vec Std.U8
  cipher_key : alloc.vec.Vec Std.U8
  seed : alloc.vec.Vec Std.U8

/-- [libsignal_protocol::sender_keys::SenderChainKey]
    Source: 'rust/protocol/src/sender_keys.rs', lines 76:0-79:1 -/
structure sender_keys.SenderChainKey where
  iteration : Std.U32
  chain_key : alloc.vec.Vec Std.U8

/-- [libsignal_protocol::sender_keys::SenderKeyState]
    Source: 'rust/protocol/src/sender_keys.rs', lines 132:0-134:1 -/
structure sender_keys.SenderKeyState where
  state : proto.storage.SenderKeyStateStructure

/-- [libsignal_protocol::sender_keys::{libsignal_protocol::sender_keys::SenderKeyState}::remove_sender_message_key::closure]
    Source: 'rust/protocol/src/sender_keys.rs', lines 229:22-229:50 -/
@[reducible]
def sender_keys.SenderKeyState.remove_sender_message_key.closure := Std.U32

/-- [libsignal_protocol::sender_keys::SenderKeyRecord]
    Source: 'rust/protocol/src/sender_keys.rs', lines 240:0-242:1
    Visibility: public -/
structure sender_keys.SenderKeyRecord where
  states : alloc.collections.vec_deque.VecDeque sender_keys.SenderKeyState
    Global

/-- [libsignal_protocol::sender_keys::{libsignal_protocol::sender_keys::SenderKeyRecord}::deserialize::closure]
    Source: 'rust/protocol/src/sender_keys.rs', lines 253:21-253:69 -/
@[reducible]
def sender_keys.SenderKeyRecord.deserialize.closure := Unit

/-- [libsignal_protocol::session_management::CurrentOrPrevious]
    Source: 'rust/protocol/src/session_management.rs', lines 712:0-717:1 -/
@[discriminant isize]
inductive session_management.CurrentOrPrevious where
| Current : session_management.CurrentOrPrevious
| Previous : session_management.CurrentOrPrevious

/-- Trait declaration: [libsignal_protocol::session_management::_::DisplayToDisplayDoc]
    Source: 'rust/protocol/src/session_management.rs', lines 711:22-711:29 -/
structure session_management._.DisplayToDisplayDoc (Self : Type) where
  __displaydoc_display : Self → Result Self

/-- Trait declaration: [libsignal_protocol::session_management::_::PathToDisplayDoc]
    Source: 'rust/protocol/src/session_management.rs', lines 711:22-711:29 -/
structure session_management._.PathToDisplayDoc (Self : Type) where
  __displaydoc_display : Self → Result std.path.Display

/-- [libsignal_protocol::state::bundle::SignedPreKey]
    Source: 'rust/protocol/src/state/bundle.rs', lines 12:0-16:1 -/
structure state.bundle.SignedPreKey where
  id : state.signed_prekey.SignedPreKeyId
  public_key : libsignal_core.curve.PublicKey
  signature : alloc.vec.Vec Std.U8

/-- [libsignal_protocol::state::bundle::KyberPreKey]
    Source: 'rust/protocol/src/state/bundle.rs', lines 29:0-33:1 -/
structure state.bundle.KyberPreKey where
  id : state.kyber_prekey.KyberPreKeyId
  public_key : kem.Key kem.Public
  signature : alloc.vec.Vec Std.U8

/-- [libsignal_protocol::state::bundle::PreKeyBundleContent]
    Source: 'rust/protocol/src/state/bundle.rs', lines 49:0-61:1
    Visibility: public -/
structure state.bundle.PreKeyBundleContent where
  registration_id : Option Std.U32
  device_id : Option libsignal_core.address.DeviceId
  pre_key_id : Option state.prekey.PreKeyId
  pre_key_public : Option libsignal_core.curve.PublicKey
  signed_pre_key_id : Option state.signed_prekey.SignedPreKeyId
  signed_pre_key_public : Option libsignal_core.curve.PublicKey
  signed_pre_key_signature : Option (alloc.vec.Vec Std.U8)
  identity_key : Option identity_key.IdentityKey
  kyber_pre_key_id : Option state.kyber_prekey.KyberPreKeyId
  kyber_pre_key_public : Option (kem.Key kem.Public)
  kyber_pre_key_signature : Option (alloc.vec.Vec Std.U8)

/-- [libsignal_protocol::state::bundle::PreKeyBundle]
    Source: 'rust/protocol/src/state/bundle.rs', lines 127:0-135:1
    Visibility: public -/
structure state.bundle.PreKeyBundle where
  registration_id : Std.U32
  device_id : libsignal_core.address.DeviceId
  pre_key_id : Option state.prekey.PreKeyId
  pre_key_public : Option libsignal_core.curve.PublicKey
  ec_signed_pre_key : state.bundle.SignedPreKey
  identity_key : identity_key.IdentityKey
  kyber_pre_key : state.bundle.KyberPreKey

/-- [libsignal_protocol::state::bundle::{impl core::convert::TryFrom<libsignal_protocol::state::bundle::PreKeyBundleContent, libsignal_protocol::error::SignalProtocolError> for libsignal_protocol::state::bundle::PreKeyBundle}::try_from::closure#9]
    Source: 'rust/protocol/src/state/bundle.rs', lines 119:44-121:13 -/
@[reducible]
def state.bundle.TryFromPreKeyBundlePreKeyBundleContentSignalProtocolError.try_from.closure_9
  :=
Unit

/-- [libsignal_protocol::state::bundle::{impl core::convert::TryFrom<libsignal_protocol::state::bundle::PreKeyBundleContent, libsignal_protocol::error::SignalProtocolError> for libsignal_protocol::state::bundle::PreKeyBundle}::try_from::closure#8]
    Source: 'rust/protocol/src/state/bundle.rs', lines 114:55-118:13 -/
@[reducible]
def state.bundle.TryFromPreKeyBundlePreKeyBundleContentSignalProtocolError.try_from.closure_8
  :=
Unit

/-- [libsignal_protocol::state::bundle::{impl core::convert::TryFrom<libsignal_protocol::state::bundle::PreKeyBundleContent, libsignal_protocol::error::SignalProtocolError> for libsignal_protocol::state::bundle::PreKeyBundle}::try_from::closure#7]
    Source: 'rust/protocol/src/state/bundle.rs', lines 111:52-113:13 -/
@[reducible]
def state.bundle.TryFromPreKeyBundlePreKeyBundleContentSignalProtocolError.try_from.closure_7
  :=
Unit

/-- [libsignal_protocol::state::bundle::{impl core::convert::TryFrom<libsignal_protocol::state::bundle::PreKeyBundleContent, libsignal_protocol::error::SignalProtocolError> for libsignal_protocol::state::bundle::PreKeyBundle}::try_from::closure#6]
    Source: 'rust/protocol/src/state/bundle.rs', lines 108:48-110:13 -/
@[reducible]
def state.bundle.TryFromPreKeyBundlePreKeyBundleContentSignalProtocolError.try_from.closure_6
  :=
Unit

/-- [libsignal_protocol::state::bundle::{impl core::convert::TryFrom<libsignal_protocol::state::bundle::PreKeyBundleContent, libsignal_protocol::error::SignalProtocolError> for libsignal_protocol::state::bundle::PreKeyBundle}::try_from::closure#5]
    Source: 'rust/protocol/src/state/bundle.rs', lines 103:56-107:13 -/
@[reducible]
def state.bundle.TryFromPreKeyBundlePreKeyBundleContentSignalProtocolError.try_from.closure_5
  :=
Unit

/-- [libsignal_protocol::state::bundle::{impl core::convert::TryFrom<libsignal_protocol::state::bundle::PreKeyBundleContent, libsignal_protocol::error::SignalProtocolError> for libsignal_protocol::state::bundle::PreKeyBundle}::try_from::closure#4]
    Source: 'rust/protocol/src/state/bundle.rs', lines 98:53-102:13 -/
@[reducible]
def state.bundle.TryFromPreKeyBundlePreKeyBundleContentSignalProtocolError.try_from.closure_4
  :=
Unit

/-- [libsignal_protocol::state::bundle::{impl core::convert::TryFrom<libsignal_protocol::state::bundle::PreKeyBundleContent, libsignal_protocol::error::SignalProtocolError> for libsignal_protocol::state::bundle::PreKeyBundle}::try_from::closure#3]
    Source: 'rust/protocol/src/state/bundle.rs', lines 95:49-97:13 -/
@[reducible]
def state.bundle.TryFromPreKeyBundlePreKeyBundleContentSignalProtocolError.try_from.closure_3
  :=
Unit

/-- [libsignal_protocol::state::bundle::{impl core::convert::TryFrom<libsignal_protocol::state::bundle::PreKeyBundleContent, libsignal_protocol::error::SignalProtocolError> for libsignal_protocol::state::bundle::PreKeyBundle}::try_from::closure#2]
    Source: 'rust/protocol/src/state/bundle.rs', lines 94:26-94:80 -/
@[reducible]
def state.bundle.TryFromPreKeyBundlePreKeyBundleContentSignalProtocolError.try_from.closure_2
  :=
  Option libsignal_core.curve.PublicKey

/-- [libsignal_protocol::state::bundle::{impl core::convert::TryFrom<libsignal_protocol::state::bundle::PreKeyBundleContent, libsignal_protocol::error::SignalProtocolError> for libsignal_protocol::state::bundle::PreKeyBundle}::try_from::closure#2::closure]
    Source: 'rust/protocol/src/state/bundle.rs', lines 94:58-94:79 -/
@[reducible]
def state.bundle.TryFromPreKeyBundlePreKeyBundleContentSignalProtocolError.try_from.closure_2.closure
  :=
  state.prekey.PreKeyId

/-- [libsignal_protocol::state::bundle::{impl core::convert::TryFrom<libsignal_protocol::state::bundle::PreKeyBundleContent, libsignal_protocol::error::SignalProtocolError> for libsignal_protocol::state::bundle::PreKeyBundle}::try_from::closure#1]
    Source: 'rust/protocol/src/state/bundle.rs', lines 89:41-91:13 -/
@[reducible]
def state.bundle.TryFromPreKeyBundlePreKeyBundleContentSignalProtocolError.try_from.closure_1
  :=
Unit

/-- [libsignal_protocol::state::bundle::{impl core::convert::TryFrom<libsignal_protocol::state::bundle::PreKeyBundleContent, libsignal_protocol::error::SignalProtocolError> for libsignal_protocol::state::bundle::PreKeyBundle}::try_from::closure]
    Source: 'rust/protocol/src/state/bundle.rs', lines 86:47-88:13 -/
@[reducible]
def state.bundle.TryFromPreKeyBundlePreKeyBundleContentSignalProtocolError.try_from.closure
  :=
Unit

/-- [libsignal_protocol::state::kyber_prekey::KyberPreKeyRecord]
    Source: 'rust/protocol/src/state/kyber_prekey.rs', lines 27:0-29:1
    Visibility: public -/
structure state.kyber_prekey.KyberPreKeyRecord where
  signed_pre_key : proto.storage.SignedPreKeyRecordStructure

/-- Trait declaration: [libsignal_protocol::state::signed_prekey::KeySerde]
    Source: 'rust/protocol/src/state/signed_prekey.rs', lines 114:0-119:1
    Visibility: public -/
structure state.signed_prekey.KeySerde (Self : Type) where
  serialize : Self → Result (alloc.vec.Vec Std.U8)
  deserialize : forall {T : Type} (coreconvertAsRefPSliceU8Inst :
    core.convert.AsRef T (Slice Std.U8)), T → Result (core.result.Result Self
    error.SignalProtocolError)

/-- Trait declaration: [libsignal_protocol::state::signed_prekey::KeyPairSerde]
    Source: 'rust/protocol/src/state/signed_prekey.rs', lines 121:0-129:1
    Visibility: public -/
structure state.signed_prekey.KeyPairSerde (Self : Type) (Self_PublicKey :
  Type) (Self_PrivateKey : Type) where
  PublicKey : state.signed_prekey.KeySerde Self_PublicKey
  PrivateKey : state.signed_prekey.KeySerde Self_PrivateKey
  from_public_and_private : Slice Std.U8 → Slice Std.U8 → Result
    (core.result.Result Self error.SignalProtocolError)
  get_public : Self → Result Self_PublicKey
  get_private : Self → Result Self_PrivateKey

/-- Trait declaration: [libsignal_protocol::state::signed_prekey::GenericSignedPreKey]
    Source: 'rust/protocol/src/state/signed_prekey.rs', lines 52:0-112:1
    Visibility: public -/
structure state.signed_prekey.GenericSignedPreKey (Self : Type) (Self_KeyPair :
  Type) (Self_Id : Type) (Self_Clause0_PublicKey : Type)
  (Self_Clause0_PrivateKey : Type) where
  KeyPairSerdeInst : state.signed_prekey.KeyPairSerde Self_KeyPair
    Self_Clause0_PublicKey Self_Clause0_PrivateKey
  coreconvertFromSelf_IdU32Inst : core.convert.From Self_Id Std.U32
  coreconvertIntoSelf_IdU32Inst : core.convert.Into Self_Id Std.U32
  get_storage : Self → Result proto.storage.SignedPreKeyRecordStructure
  from_storage : proto.storage.SignedPreKeyRecordStructure → Result Self
  new : Self_Id → timestamp.Timestamp → Self_KeyPair → Slice Std.U8 →
    Result Self
  serialize : Self → Result (core.result.Result (alloc.vec.Vec Std.U8)
    error.SignalProtocolError)
  deserialize : Slice Std.U8 → Result (core.result.Result Self
    error.SignalProtocolError)
  id : Self → Result (core.result.Result Self_Id error.SignalProtocolError)
  timestamp : Self → Result (core.result.Result timestamp.Timestamp
    error.SignalProtocolError)
  signature : Self → Result (core.result.Result (alloc.vec.Vec Std.U8)
    error.SignalProtocolError)
  public_key : Self → Result (core.result.Result Self_Clause0_PublicKey
    error.SignalProtocolError)
  key_pair : Self → Result (core.result.Result Self_KeyPair
    error.SignalProtocolError)

/-- [libsignal_protocol::state::prekey::PreKeyRecord]
    Source: 'rust/protocol/src/state/prekey.rs', lines 26:0-28:1
    Visibility: public -/
structure state.prekey.PreKeyRecord where
  pre_key : proto.storage.PreKeyRecordStructure

/-- [libsignal_protocol::state::prekey::{libsignal_protocol::state::prekey::PreKeyRecord}::deserialize::closure]
    Source: 'rust/protocol/src/state/prekey.rs', lines 46:25-46:73 -/
@[reducible]
def state.prekey.PreKeyRecord.deserialize.closure := Unit

/-- [libsignal_protocol::state::session::UnacknowledgedPreKeyMessageItems]
    Source: 'rust/protocol/src/state/session.rs', lines 42:0-52:1 -/
structure state.session.UnacknowledgedPreKeyMessageItems where
  pre_key_id : Option state.prekey.PreKeyId
  signed_pre_key_id : state.signed_prekey.SignedPreKeyId
  base_key : libsignal_core.curve.PublicKey
  kyber_pre_key_id : Option state.kyber_prekey.KyberPreKeyId
  kyber_ciphertext : Option (Slice Std.U8)
  timestamp : std.time.SystemTime

/-- [libsignal_protocol::state::session::SessionUsabilityRequirements]
    Source: 'rust/protocol/src/state/session.rs', lines 146:0-146:45
    Visibility: public -/
@[reducible]
def state.session.SessionUsabilityRequirements := Std.U32

/-- [libsignal_protocol::state::session::{libsignal_protocol::state::session::SessionState}::all_receiver_chain_logging_info::closure]
    Source: 'rust/protocol/src/state/session.rs', lines 327:61-327:88 -/
@[reducible]
def state.session.SessionState.all_receiver_chain_logging_info.closure := Unit

/-- [libsignal_protocol::state::session::{libsignal_protocol::state::session::SessionRecord}::serialize::closure]
    Source: 'rust/protocol/src/state/session.rs', lines 865:63-865:75 -/
@[reducible]
def state.session.SessionRecord.serialize.closure := Unit

/-- [libsignal_protocol::state::signed_prekey::SignedPreKeyRecord]
    Source: 'rust/protocol/src/state/signed_prekey.rs', lines 27:0-29:1
    Visibility: public -/
structure state.signed_prekey.SignedPreKeyRecord where
  signed_pre_key : proto.storage.SignedPreKeyRecordStructure

/-- [libsignal_protocol::triple_ratchet::OutgoingTripleRatchet]
    Source: 'rust/protocol/src/triple_ratchet.rs', lines 41:0-49:1 -/
structure triple_ratchet.OutgoingTripleRatchet where
  sender_ratchet_key : libsignal_core.curve.KeyPair
  sender_chain_key : ratchet.keys.ChainKey
  previous_counter : Std.U32
  pqr_state : alloc.vec.Vec Std.U8
  session_version : Std.U8
  local_identity_key : identity_key.IdentityKey
  remote_identity_key : identity_key.IdentityKey

/-- [libsignal_protocol::triple_ratchet::TripleRatchet]
    Source: 'rust/protocol/src/triple_ratchet.rs', lines 160:0-165:1 -/
structure triple_ratchet.TripleRatchet where
  ratchet : double_ratchet.RatchetState
  pqr_state : alloc.vec.Vec Std.U8
  local_identity_key : identity_key.IdentityKey
  remote_identity_key : identity_key.IdentityKey

end libsignal_protocol
