import VersoManual
import Book.Annotation
import Book.CodeRef
import Book.RustCode

open Verso.Genre Manual

#doc (Manual) "Security Considerations" =>

# The Vulnerable Message Set

This protocol is designed to provide robust continuous key agreement in the presence of bandwidth limits. Since many messages must be passed in order to reach key agreement, the important measure of security provided by this protocol is "in the event of a compromise, how many messages are passed before healing?". We call this the _vulnerable message set_.

The size of the vulnerable message set is not an intrinsic property of the protocol. For the ML-KEM Braid, given a chunk size and choice of KEM one can compute the _minimum_ possible size of the vulnerable message set, but the _maximum_ size of this set is unbounded: if Bob never replies to Alice but Alice continues sending messages, their session will never heal and all of Alice's messages will be vulnerable.

In fact, as shown in [\[3\]](https://signal.org/docs/specifications/mlkembraid/#ref-comparesm), the size of the vulnerable message set for a SCKA protocol depends on the message sending behavior of the protocol participants. Two parties that are online and in rapid conversation, such as two parties chatting using their primary devices in a Signal chat, will typically have a smaller vulnerable message set than will be found in a conversation between two parties on desktop devices that are often offline.

The ML-KEM Braid protocol was selected to provide small vulnerable message sets in a wide range of realistic secure messaging scenarios, but for applications with highly specific message sending behaviors protocol designers should consider whether a different SCKA protocol may provide better security.

# {galois}[Important Note on Post-Compromise Security]

:::galois
One thing that the Signal docs do not emphasize enough here is that the security guarantees of the Sparse Post-Quantum Ratchet (SPQR) enhance rather than replace the Post-Compromise Security (Backward Security) of the original Double Ratchet protocol. Meaning that an adversary needs to break both the original Double Ratchet protocol and the SPQR protocol in order to break PCS. The vulnerable set described above is only vulnerable in the presence of a post-quantum adversary that can break the Double Ratchet protocol to begin with.

In more detail, the message key generated by the SPQR protocol is mixed with the Double Ratchet mechanism for that epoch {galoisnote}[{libsignal "rust/protocol/src/triple_ratchet.rs#L254"}[], {spqr "src/v1/chunked/states.rs#L207"}[]]. 
:::

# Encoder domain size

\[...\]

We recommend using _GF(2^16)_ as the underlying field. {galoisnote}[This is what libsignal's SPQR uses itself: {spqr "src/encoding/gf.rs#L16"}[].] When using ML-KEM 768 [\[1\]](https://signal.org/docs/specifications/mlkembraid/#ref-kyberfips203) as the underlying KEM and 32-byte codewords, the largest message sent by the protocol is 36 codewords long. Thus to prevent ratcheting, an attacker must prevent 216 - 35 out of every 216 messages from being delivered. While this is not a complete denial of service, it requires blocking over 99.9% of messages and will likely cause protocol users to consider the underlying service to be unavailable.

\[...\]

# Representation of epochs

If an implementation uses a fixed width integer to represent the epoch, then eventually the epoch counter will repeat and the protocol loses the property that every epoch produces a unique key. For example, an application that uses 8-bit integers for epochs to conserve space in protocol messages will begin repeating epochs after 256 keys have been emitted - something that is likely to happen in many conversations. Using a 64-bit integer to represent the epoch will prevent this wraparound from ever happening in a human conversation, but for other applications of the ML-KEM Braid this wraparound should be considered. {galoisnote}[libsignal's SPQR relies on 64 bit integer representation of epochs: {spqr "src/lib.rs#L39"}[].]
