-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libsignal_core]: function definitions
import Aeneas
import PQXDH.Aeneas2.Extracted.Core.Types
import PQXDH.Aeneas2.Extracted.Core.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.longLine false
set_option linter.style.setOption false
set_option linter.style.whitespace false
set_option linter.style.nameCheck false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace libsignal_core

/-- Trait implementation: [core::num::niche_types::{impl core::clone::Clone for core::num::niche_types::NonZeroU64Inner}]
    Source: '/rustc/library/core/src/num/niche_types.rs', lines 17:17-17:22
    Name pattern: [core::clone::Clone<core::num::niche_types::NonZeroU64Inner>] -/
@[reducible, rust_trait_impl
  "core::clone::Clone<core::num::niche_types::NonZeroU64Inner>"]
def core.num.niche_types.NonZeroU64Inner.Insts.CoreCloneClone :
  core.clone.Clone core.num.niche_types.NonZeroU64Inner := {
  clone := core.num.niche_types.NonZeroU64Inner.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [core::num::niche_types::{impl core::clone::Clone for core::num::niche_types::NonZeroU8Inner}]
    Source: '/rustc/library/core/src/num/niche_types.rs', lines 17:17-17:22
    Name pattern: [core::clone::Clone<core::num::niche_types::NonZeroU8Inner>] -/
@[reducible, rust_trait_impl
  "core::clone::Clone<core::num::niche_types::NonZeroU8Inner>"]
def core.num.niche_types.NonZeroU8Inner.Insts.CoreCloneClone : core.clone.Clone
  core.num.niche_types.NonZeroU8Inner := {
  clone := core.num.niche_types.NonZeroU8Inner.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [core::num::niche_types::{impl core::marker::Copy for core::num::niche_types::NonZeroU64Inner}]
    Source: '/rustc/library/core/src/num/niche_types.rs', lines 17:24-17:28
    Name pattern: [core::marker::Copy<core::num::niche_types::NonZeroU64Inner>] -/
@[reducible, rust_trait_impl
  "core::marker::Copy<core::num::niche_types::NonZeroU64Inner>"]
def core.num.niche_types.NonZeroU64Inner.Insts.CoreMarkerCopy :
  core.marker.Copy core.num.niche_types.NonZeroU64Inner := {
  cloneInst := core.num.niche_types.NonZeroU64Inner.Insts.CoreCloneClone
}

/-- Trait implementation: [core::num::niche_types::{impl core::marker::Copy for core::num::niche_types::NonZeroU8Inner}]
    Source: '/rustc/library/core/src/num/niche_types.rs', lines 17:24-17:28
    Name pattern: [core::marker::Copy<core::num::niche_types::NonZeroU8Inner>] -/
@[reducible, rust_trait_impl
  "core::marker::Copy<core::num::niche_types::NonZeroU8Inner>"]
def core.num.niche_types.NonZeroU8Inner.Insts.CoreMarkerCopy : core.marker.Copy
  core.num.niche_types.NonZeroU8Inner := {
  cloneInst := core.num.niche_types.NonZeroU8Inner.Insts.CoreCloneClone
}

/-- Trait implementation: [core::num::nonzero::{impl core::num::nonzero::private::Sealed for u64}]
    Source: '/rustc/library/core/src/num/nonzero.rs', lines 56:12-56:47
    Name pattern: [core::num::nonzero::private::Sealed<u64>] -/
@[reducible, rust_trait_impl "core::num::nonzero::private::Sealed<u64>"]
def U64.Insts.CoreNumNonzeroPrivateSealed : core.num.nonzero.private.Sealed
  Std.U64 := {
}

/-- Trait implementation: [core::num::nonzero::{impl core::num::nonzero::private::Sealed for u8}]
    Source: '/rustc/library/core/src/num/nonzero.rs', lines 56:12-56:47
    Name pattern: [core::num::nonzero::private::Sealed<u8>] -/
@[reducible, rust_trait_impl "core::num::nonzero::private::Sealed<u8>"]
def U8.Insts.CoreNumNonzeroPrivateSealed : core.num.nonzero.private.Sealed
  Std.U8 := {
}

/-- Trait implementation: [core::num::nonzero::{impl core::num::nonzero::ZeroablePrimitive<core::num::niche_types::NonZeroU64Inner> for u64}]
    Source: '/rustc/library/core/src/num/nonzero.rs', lines 63:12-63:56
    Name pattern: [core::num::nonzero::ZeroablePrimitive<u64, core::num::niche_types::NonZeroU64Inner>] -/
@[reducible, rust_trait_impl
  "core::num::nonzero::ZeroablePrimitive<u64, core::num::niche_types::NonZeroU64Inner>"]
def U64.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroU64Inner :
  core.num.nonzero.ZeroablePrimitive Std.U64
  core.num.niche_types.NonZeroU64Inner := {
  markerCopyInst := core.marker.CopyU64
  privateSealedInst := U64.Insts.CoreNumNonzeroPrivateSealed
  markerCopyInst1 := core.num.niche_types.NonZeroU64Inner.Insts.CoreMarkerCopy
}

/-- Trait implementation: [core::num::nonzero::{impl core::num::nonzero::ZeroablePrimitive<core::num::niche_types::NonZeroU8Inner> for u8}]
    Source: '/rustc/library/core/src/num/nonzero.rs', lines 63:12-63:56
    Name pattern: [core::num::nonzero::ZeroablePrimitive<u8, core::num::niche_types::NonZeroU8Inner>] -/
@[reducible, rust_trait_impl
  "core::num::nonzero::ZeroablePrimitive<u8, core::num::niche_types::NonZeroU8Inner>"]
def U8.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroU8Inner :
  core.num.nonzero.ZeroablePrimitive Std.U8 core.num.niche_types.NonZeroU8Inner
  := {
  markerCopyInst := core.marker.CopyU8
  privateSealedInst := U8.Insts.CoreNumNonzeroPrivateSealed
  markerCopyInst1 := core.num.niche_types.NonZeroU8Inner.Insts.CoreMarkerCopy
}

/-- [libsignal_core::address::{impl core::cmp::PartialEq<libsignal_core::address::ServiceIdKind> for libsignal_core::address::ServiceIdKind}::eq]:
    Source: 'rust/core/src/address.rs', lines 16:28-16:37
    Visibility: public -/
def address.ServiceIdKind.Insts.CoreCmpPartialEqServiceIdKind.eq
  (self : address.ServiceIdKind) (other : address.ServiceIdKind) :
  Result Bool
  := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- [libsignal_core::address::{impl core::convert::TryFrom<u8, derive_more::convert::try_from::TryFromReprError<u8>> for libsignal_core::address::ServiceIdKind}::try_from]:
    Source: 'rust/core/src/address.rs', lines 16:43-16:63
    Visibility: public -/
def address.ServiceIdKind.Insts.CoreConvertTryFromU8TryFromReprErrorU8.try_from
  (val : Std.U8) :
  Result (core.result.Result address.ServiceIdKind
    (derive_more.convert.try_from.TryFromReprError Std.U8))
  := do
  match val with
  | 0#uscalar => ok (core.result.Result.Ok address.ServiceIdKind.Aci)
  | 1#uscalar => ok (core.result.Result.Ok address.ServiceIdKind.Pni)
  | _ =>
    let tfre ← derive_more.convert.try_from.TryFromReprError.new val
    ok (core.result.Result.Err tfre)

/-- [libsignal_core::address::{impl core::convert::From<libsignal_core::address::ServiceIdKind> for u8}::from]:
    Source: 'rust/core/src/address.rs', lines 27:4-29:5
    Visibility: public -/
def U8.Insts.CoreConvertFromServiceIdKind.from
  (value : address.ServiceIdKind) : Result Std.U8 := do
  let value1 := read_discriminant value
  ok (UScalar.cast .U8 value1)

/-- Trait implementation: [libsignal_core::address::{impl core::convert::From<libsignal_core::address::ServiceIdKind> for u8}]
    Source: 'rust/core/src/address.rs', lines 26:0-30:1 -/
@[reducible]
def U8.Insts.CoreConvertFromServiceIdKind : core.convert.From Std.U8
  address.ServiceIdKind := {
  «from» := U8.Insts.CoreConvertFromServiceIdKind.from
}

/-- [libsignal_core::address::{libsignal_core::address::SpecificServiceId<KIND>}::from_uuid]:
    Source: 'rust/core/src/address.rs', lines 77:4-79:5 -/
def address.SpecificServiceId.from_uuid
  (KIND : Std.U8) (uuid : uuid.Uuid) :
  Result (address.SpecificServiceId KIND)
  := do
  ok { uuid }

/-- [libsignal_core::address::{libsignal_core::address::SpecificServiceId<KIND>}::from_uuid_bytes]:
    Source: 'rust/core/src/address.rs', lines 72:4-74:5
    Visibility: public -/
def address.SpecificServiceId.from_uuid_bytes
  (KIND : Std.U8) (bytes : Array Std.U8 16#usize) :
  Result (address.SpecificServiceId KIND)
  := do
  let u ← uuid.builder.Uuid.from_bytes bytes
  address.SpecificServiceId.from_uuid KIND u

/-- [libsignal_core::address::{impl core::convert::From<libsignal_core::address::SpecificServiceId<KIND>> for uuid::Uuid}::from]:
    Source: 'rust/core/src/address.rs', lines 151:4-153:5
    Visibility: public -/
def uuid.Uuid.Insts.CoreConvertFromSpecificServiceId.from
  {KIND : Std.U8} (value : address.SpecificServiceId KIND) :
  Result uuid.Uuid
  := do
  ok value.uuid

/-- Trait implementation: [libsignal_core::address::{impl core::convert::From<libsignal_core::address::SpecificServiceId<KIND>> for uuid::Uuid}]
    Source: 'rust/core/src/address.rs', lines 149:0-154:1 -/
@[reducible]
def uuid.Uuid.Insts.CoreConvertFromSpecificServiceId (KIND : Std.U8) :
  core.convert.From uuid.Uuid (address.SpecificServiceId KIND) := {
  «from» := uuid.Uuid.Insts.CoreConvertFromSpecificServiceId.from
}

/-- [libsignal_core::address::{libsignal_core::address::ServiceId}::raw_uuid]:
    Source: 'rust/core/src/address.rs', lines 288:4-293:5
    Visibility: public -/
def address.ServiceId.raw_uuid
  (self : address.ServiceId) : Result uuid.Uuid := do
  match self with
  | address.ServiceId.Aci aci =>
    core.convert.IntoFrom.into
      (uuid.Uuid.Insts.CoreConvertFromSpecificServiceId 0#u8) aci
  | address.ServiceId.Pni pni =>
    core.convert.IntoFrom.into
      (uuid.Uuid.Insts.CoreConvertFromSpecificServiceId 1#u8) pni

/-- [libsignal_core::address::{libsignal_core::address::ServiceId}::kind]:
    Source: 'rust/core/src/address.rs', lines 195:4-200:5
    Visibility: public -/
def address.ServiceId.kind
  (self : address.ServiceId) : Result address.ServiceIdKind := do
  match self with
  | address.ServiceId.Aci _ => ok address.ServiceIdKind.Aci
  | address.ServiceId.Pni _ => ok address.ServiceIdKind.Pni

/-- [libsignal_core::address::{libsignal_core::address::ServiceId}::service_id_fixed_width_binary]:
    Source: 'rust/core/src/address.rs', lines 216:4-221:5
    Visibility: public -/
def address.ServiceId.service_id_fixed_width_binary
  (self : address.ServiceId) : Result (Array Std.U8 17#usize) := do
  let result := Array.repeat 17#usize 0#u8
  let sik ← address.ServiceId.kind self
  let i ←
    core.convert.IntoFrom.into U8.Insts.CoreConvertFromServiceIdKind sik
  let result1 ← Array.update result 0#usize i
  let (s, index_mut_back) ←
    core.array.Array.index_mut (core.ops.index.IndexMutSlice
      (core.slice.index.SliceIndexRangeFromUsizeSlice Std.U8)) result1
      { start := 1#usize }
  let u ← address.ServiceId.raw_uuid self
  let a ← uuid.Uuid.as_bytes u
  let s1 ← lift (Array.to_slice a)
  let s2 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s s1
  ok (index_mut_back s2)

/-- [libsignal_core::address::{libsignal_core::address::ServiceId}::service_id_binary]:
    Source: 'rust/core/src/address.rs', lines 206:4-212:5
    Visibility: public -/
def address.ServiceId.service_id_binary
  (self : address.ServiceId) : Result (alloc.vec.Vec Std.U8) := do
  match self with
  | address.ServiceId.Aci aci =>
    let a ← uuid.Uuid.as_bytes aci.uuid
    let s ← lift (Array.to_slice a)
    alloc.slice.Slice.to_vec core.clone.CloneU8 s
  | address.ServiceId.Pni _ =>
    let a ← address.ServiceId.service_id_fixed_width_binary self
    let s ← lift (Array.to_slice a)
    alloc.slice.Slice.to_vec core.clone.CloneU8 s

/-- [libsignal_core::address::{libsignal_core::address::SpecificServiceId<KIND>}::service_id_binary]:
    Source: 'rust/core/src/address.rs', lines 99:4-101:5
    Visibility: public -/
def address.SpecificServiceId.service_id_binary
  {Clause1_Error : Type} {KIND : Std.U8}
  (coreconvertFromServiceIdSpecificServiceIdInst : core.convert.From
  address.ServiceId (address.SpecificServiceId KIND))
  (coreconvertTryFromSpecificServiceIdServiceIdClause1_ErrorInst :
  core.convert.TryFrom (address.SpecificServiceId KIND) address.ServiceId
  Clause1_Error) (self : address.SpecificServiceId KIND) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let si ← coreconvertFromServiceIdSpecificServiceIdInst.«from» self
  address.ServiceId.service_id_binary si

/-- [libsignal_core::address::{libsignal_core::address::SpecificServiceId<KIND>}::service_id_fixed_width_binary]:
    Source: 'rust/core/src/address.rs', lines 105:4-107:5
    Visibility: public -/
def address.SpecificServiceId.service_id_fixed_width_binary
  {Clause1_Error : Type} {KIND : Std.U8}
  (coreconvertFromServiceIdSpecificServiceIdInst : core.convert.From
  address.ServiceId (address.SpecificServiceId KIND))
  (coreconvertTryFromSpecificServiceIdServiceIdClause1_ErrorInst :
  core.convert.TryFrom (address.SpecificServiceId KIND) address.ServiceId
  Clause1_Error) (self : address.SpecificServiceId KIND) :
  Result (Array Std.U8 17#usize)
  := do
  let si ← coreconvertFromServiceIdSpecificServiceIdInst.«from» self
  address.ServiceId.service_id_fixed_width_binary si

/-- [libsignal_core::address::{impl core::convert::From<uuid::Uuid> for libsignal_core::address::SpecificServiceId<KIND>}::from]:
    Source: 'rust/core/src/address.rs', lines 144:4-146:5
    Visibility: public -/
def address.SpecificServiceId.Insts.CoreConvertFromUuid.from
  (KIND : Std.U8) (value : uuid.Uuid) :
  Result (address.SpecificServiceId KIND)
  := do
  address.SpecificServiceId.from_uuid KIND value

/-- Trait implementation: [libsignal_core::address::{impl core::convert::From<uuid::Uuid> for libsignal_core::address::SpecificServiceId<KIND>}]
    Source: 'rust/core/src/address.rs', lines 142:0-147:1 -/
@[reducible]
def address.SpecificServiceId.Insts.CoreConvertFromUuid (KIND : Std.U8) :
  core.convert.From (address.SpecificServiceId KIND) uuid.Uuid := {
  «from» := address.SpecificServiceId.Insts.CoreConvertFromUuid.from KIND
}

/-- [libsignal_core::address::{libsignal_core::address::ServiceId}::parse_from_service_id_fixed_width_binary]:
    Source: 'rust/core/src/address.rs', lines 254:4-262:5
    Visibility: public -/
def address.ServiceId.parse_from_service_id_fixed_width_binary
  (bytes : Array Std.U8 17#usize) : Result (Option address.ServiceId) := do
  let s ←
    core.array.Array.index (core.ops.index.IndexSlice
      (core.slice.index.SliceIndexRangeFromUsizeSlice Std.U8)) bytes
      { start := 1#usize }
  let r ← uuid.builder.Uuid.from_slice s
  let o ← core.result.Result.ok r
  let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let i ← Array.index_usize bytes 0#usize
    let r1 ←
      address.ServiceIdKind.Insts.CoreConvertTryFromU8TryFromReprErrorU8.try_from
        i
    let o1 ← core.result.Result.ok r1
    let cf1 ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      match val1 with
      | address.ServiceIdKind.Aci =>
        let ssi ←
          core.convert.IntoFrom.into
            (address.SpecificServiceId.Insts.CoreConvertFromUuid 0#u8) val
        ok (some (address.ServiceId.Aci ssi))
      | address.ServiceIdKind.Pni =>
        let ssi ←
          core.convert.IntoFrom.into
            (address.SpecificServiceId.Insts.CoreConvertFromUuid 1#u8) val
        ok (some (address.ServiceId.Pni ssi))
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
        address.ServiceId residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
      address.ServiceId residual

/-- [libsignal_core::address::{libsignal_core::address::ServiceId}::parse_from_service_id_binary]:
    Source: 'rust/core/src/address.rs', lines 234:4-250:5
    Visibility: public -/
def address.ServiceId.parse_from_service_id_binary
  (bytes : Slice Std.U8) : Result (Option address.ServiceId) := do
  let i := Slice.len bytes
  match i.val with
  | 16 =>
    let r ← uuid.builder.Uuid.from_slice bytes
    let o ← core.result.Result.ok r
    let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let ssi ←
        core.convert.IntoFrom.into
          (address.SpecificServiceId.Insts.CoreConvertFromUuid 0#u8) val
      ok (some (address.ServiceId.Aci ssi))
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
        address.ServiceId residual
  | 17 =>
    let r ← core.array.TryFromSharedArraySlice.try_from 17#usize bytes
    let a ←
      core.result.Result.expect core.fmt.DebugTryFromSliceError r (toStr
        "already measured")
    let o ← address.ServiceId.parse_from_service_id_fixed_width_binary a
    let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let sik ← address.ServiceId.kind val
      let b ←
        address.ServiceIdKind.Insts.CoreCmpPartialEqServiceIdKind.eq sik
          address.ServiceIdKind.Aci
      if b
      then ok none
      else ok (some val)
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
        address.ServiceId residual
  | _ => ok none

/-- [libsignal_core::address::{libsignal_core::address::SpecificServiceId<KIND>}::parse_from_service_id_binary]:
    Source: 'rust/core/src/address.rs', lines 116:4-120:5
    Visibility: public -/
def address.SpecificServiceId.parse_from_service_id_binary
  {Clause1_Error : Type} {KIND : Std.U8}
  (coreconvertFromServiceIdSpecificServiceIdInst : core.convert.From
  address.ServiceId (address.SpecificServiceId KIND))
  (coreconvertTryFromSpecificServiceIdServiceIdClause1_ErrorInst :
  core.convert.TryFrom (address.SpecificServiceId KIND) address.ServiceId
  Clause1_Error) (bytes : Slice Std.U8) :
  Result (Option (address.SpecificServiceId KIND))
  := do
  let o ← address.ServiceId.parse_from_service_id_binary bytes
  let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let r ←
      core.convert.TryInto.Blanket.try_into
        coreconvertTryFromSpecificServiceIdServiceIdClause1_ErrorInst val
    core.result.Result.ok r
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
      (address.SpecificServiceId KIND) residual

/-- [libsignal_core::address::{libsignal_core::address::SpecificServiceId<KIND>}::parse_from_service_id_fixed_width_binary]:
    Source: 'rust/core/src/address.rs', lines 124:4-130:5
    Visibility: public -/
def address.SpecificServiceId.parse_from_service_id_fixed_width_binary
  {Clause1_Error : Type} {KIND : Std.U8}
  (coreconvertFromServiceIdSpecificServiceIdInst : core.convert.From
  address.ServiceId (address.SpecificServiceId KIND))
  (coreconvertTryFromSpecificServiceIdServiceIdClause1_ErrorInst :
  core.convert.TryFrom (address.SpecificServiceId KIND) address.ServiceId
  Clause1_Error) (bytes : Array Std.U8 17#usize) :
  Result (Option (address.SpecificServiceId KIND))
  := do
  let o ← address.ServiceId.parse_from_service_id_fixed_width_binary bytes
  let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let r ←
      core.convert.TryInto.Blanket.try_into
        coreconvertTryFromSpecificServiceIdServiceIdClause1_ErrorInst val
    core.result.Result.ok r
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
      (address.SpecificServiceId KIND) residual

/-- [libsignal_core::address::MAX_VALID_DEVICE_ID]
    Source: 'rust/core/src/address.rs', lines 719:0-719:36 -/
@[global_simps, irreducible] def address.MAX_VALID_DEVICE_ID : Std.U8 := 127#u8

/-- [libsignal_core::address::{libsignal_core::address::DeviceId}::new_nonzero]:
    Source: 'rust/core/src/address.rs', lines 710:4-716:5
    Visibility: public -/
def address.DeviceId.new_nonzero
  (id : core.num.nonzero.NonZero Std.U8 core.num.niche_types.NonZeroU8Inner) :
  Result (core.result.Result address.DeviceId address.InvalidDeviceId)
  := do
  let i ←
    core.num.nonzero.NonZero.get
      U8.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroU8Inner id
  if i <= address.MAX_VALID_DEVICE_ID
  then ok (core.result.Result.Ok { id })
  else ok (core.result.Result.Err ())

/-- [libsignal_core::address::{libsignal_core::address::DeviceId}::new]:
    Source: 'rust/core/src/address.rs', lines 699:4-704:5
    Visibility: public -/
def address.DeviceId.new
  (id : Std.U8) :
  Result (core.result.Result address.DeviceId address.InvalidDeviceId)
  := do
  let o ←
    core.num.nonzero.NonZero.new
      U8.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroU8Inner id
  match o with
  | none => ok (core.result.Result.Err ())
  | some id1 => address.DeviceId.new_nonzero id1

/-- [libsignal_core::address::{libsignal_core::address::ProtocolAddress}::new]:
    Source: 'rust/core/src/address.rs', lines 802:4-804:5
    Visibility: public -/
def address.ProtocolAddress.new
  (name1 : String) (device_id : address.DeviceId) :
  Result address.ProtocolAddress
  := do
  ok { «name» := name1, device_id }

/-- [libsignal_core::address::{libsignal_core::address::ProtocolAddress}::name]:
    Source: 'rust/core/src/address.rs', lines 808:4-810:5
    Visibility: public -/
def address.ProtocolAddress.impl.name
  (self : address.ProtocolAddress) : Result Str := do
  alloc.string.String.Insts.CoreOpsDerefDerefStr.deref self.«name»

/-- [libsignal_core::address::{libsignal_core::address::ProtocolAddress}::device_id]:
    Source: 'rust/core/src/address.rs', lines 818:4-820:5
    Visibility: public -/
def address.ProtocolAddress.impl.device_id
  (self : address.ProtocolAddress) : Result address.DeviceId := do
  ok self.device_id

/-- [libsignal_core::curve::{libsignal_core::curve::KeyType}::value]:
    Source: 'rust/core/src/curve.rs', lines 26:4-30:5 -/
def curve.KeyType.value (self : curve.KeyType) : Result Std.U8 := do
  ok 5#u8

/-- [libsignal_core::curve::{libsignal_core::curve::PublicKey}::public_key_bytes]:
    Source: 'rust/core/src/curve.rs', lines 107:4-111:5
    Visibility: public -/
def curve.PublicKey.public_key_bytes
  (self : curve.PublicKey) : Result (Slice Std.U8) := do
  let ⟨ v ⟩ := self.key
  ok (Array.to_slice v)

/-- [libsignal_core::curve::{libsignal_core::curve::PublicKey}::from_djb_public_key_bytes]:
    Source: 'rust/core/src/curve.rs', lines 113:4-120:5
    Visibility: public -/
def curve.PublicKey.from_djb_public_key_bytes
  (bytes : Slice Std.U8) :
  Result (core.result.Result curve.PublicKey curve.CurveError)
  := do
  let r ←
    core.array.TryFromArrayCopySlice.try_from 32#usize core.marker.CopyU8 bytes
  match r with
  | core.result.Result.Ok key =>
    ok (core.result.Result.Ok
      { key := (curve.PublicKeyData.DjbPublicKey key) })
  | core.result.Result.Err _ =>
    let i := Slice.len bytes
    ok (core.result.Result.Err (curve.CurveError.BadKeyLength curve.KeyType.Djb
      i))

/-- [libsignal_core::curve::{libsignal_core::curve::PublicKey}::key_type]:
    Source: 'rust/core/src/curve.rs', lines 159:4-163:5
    Visibility: public -/
def curve.PublicKey.key_type
  (self : curve.PublicKey) : Result curve.KeyType := do
  ok curve.KeyType.Djb

/-- [libsignal_core::curve::{libsignal_core::curve::PublicKey}::serialize]:
    Source: 'rust/core/src/curve.rs', lines 122:4-132:5
    Visibility: public -/
def curve.PublicKey.serialize
  (self : curve.PublicKey) : Result (Slice Std.U8) := do
  let ⟨ v ⟩ := self.key
  let s ← lift (Array.to_slice v)
  let value_len := Slice.len s
  let i ← 1#usize + value_len
  let result := alloc.vec.Vec.with_capacity Std.U8 i
  let kt ← curve.PublicKey.key_type { key := self.key }
  let i1 ← curve.KeyType.value kt
  let result1 ← alloc.vec.Vec.push result i1
  let s1 ← lift (Array.to_slice v)
  let result2 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 result1 s1
  alloc.vec.Vec.into_boxed_slice Global result2

/-- [libsignal_core::curve::{libsignal_core::curve::PublicKey}::verify_signature]:
    Source: 'rust/core/src/curve.rs', lines 134:4-136:5
    Visibility: public -/
def curve.PublicKey.verify_signature
  (self : curve.PublicKey) (message : Slice Std.U8) (signature : Slice Std.U8)
  :
  Result Bool
  := do
  let s ← lift (Array.to_slice (Array.make 1#usize [ message ]))
  curve.PublicKey.verify_signature_for_multipart_message self s signature

/-- [libsignal_core::curve::{libsignal_core::curve::PublicKey}::scalar_is_in_range]:
    Source: 'rust/core/src/curve.rs', lines 176:4-186:5 -/
def curve.PublicKey.scalar_is_in_range
  (self : curve.PublicKey) : Result Bool := do
  let ⟨ k ⟩ := self.key
  let i ← Array.index_usize k 31#usize
  let i1 ← lift (i &&& 128#u8)
  let b ←
    if i1 != 0#u8
    then ok true
    else
      do
      let i2 ← Array.index_usize k 0#usize
      let i3 ← lift (core.num.U8.wrapping_sub 0#u8 19#u8)
      if i2 >= i3
      then
        let s ←
          core.array.Array.index (core.ops.index.IndexSlice
            (core.slice.index.SliceIndexRangeUsizeSlice Std.U8)) k
            { start := 1#usize, «end» := 31#usize }
        let a := Array.repeat 30#usize 255#u8
        let b1 ←
          Slice.Insts.CoreCmpPartialEqArray.eq core.cmp.PartialEqU8 s a
        if b1
        then ok (i == 127#u8)
        else ok false
      else ok false
  ok (¬ b)

/-- [libsignal_core::curve::{libsignal_core::curve::PublicKey}::is_canonical]:
    Source: 'rust/core/src/curve.rs', lines 188:4-190:5
    Visibility: public -/
def curve.PublicKey.is_canonical (self : curve.PublicKey) : Result Bool := do
  let b ← curve.PublicKey.is_torsion_free self
  if b
  then curve.PublicKey.scalar_is_in_range self
  else ok false

/-- [libsignal_core::curve::{libsignal_core::curve::PrivateKey}::serialize]:
    Source: 'rust/core/src/curve.rs', lines 253:4-257:5
    Visibility: public -/
def curve.PrivateKey.serialize
  (self : curve.PrivateKey) : Result (alloc.vec.Vec Std.U8) := do
  let ⟨ v ⟩ := self.key
  let s ← lift (Array.to_slice v)
  alloc.slice.Slice.to_vec core.clone.CloneU8 s

/-- [libsignal_core::curve::{libsignal_core::curve::PrivateKey}::key_type]:
    Source: 'rust/core/src/curve.rs', lines 269:4-273:5
    Visibility: public -/
def curve.PrivateKey.key_type
  (self : curve.PrivateKey) : Result curve.KeyType := do
  ok curve.KeyType.Djb

/-- [libsignal_core::curve::{libsignal_core::curve::KeyPair}::from_public_and_private]:
    Source: 'rust/core/src/curve.rs', lines 350:4-360:5
    Visibility: public -/
def curve.KeyPair.from_public_and_private
  (public_key : Slice Std.U8) (private_key : Slice Std.U8) :
  Result (core.result.Result curve.KeyPair curve.CurveError)
  := do
  let r ←
    curve.PublicKey.Insts.CoreConvertTryFromShared0SliceU8CurveError.try_from
      public_key
  let cf ← core.result.Result.Insts.CoreOpsTry_traitTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let r1 ←
      curve.PrivateKey.Insts.CoreConvertTryFromShared0SliceU8CurveError.try_from
        private_key
    let cf1 ← core.result.Result.Insts.CoreOpsTry_traitTry.branch r1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      ok (core.result.Result.Ok { public_key := val, private_key := val1 })
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
        curve.KeyPair (core.convert.FromSame curve.CurveError) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
      curve.KeyPair (core.convert.FromSame curve.CurveError) residual

/-- [libsignal_core::e164::{libsignal_core::e164::E164}::new]:
    Source: 'rust/core/src/e164.rs', lines 18:4-20:5
    Visibility: public -/
def e164.E164.new
  (number : core.num.nonzero.NonZero Std.U64
  core.num.niche_types.NonZeroU64Inner) :
  Result e164.E164
  := do
  ok { inner := number }

/-- [libsignal_core::e164::{libsignal_core::e164::E164}::to_be_bytes]:
    Source: 'rust/core/src/e164.rs', lines 22:4-24:5
    Visibility: public -/
def e164.E164.to_be_bytes
  (self : e164.E164) : Result (Array Std.U8 8#usize) := do
  let i ←
    core.num.nonzero.NonZero.get
      U64.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroU64Inner self.inner
  ok (core.num.U64.to_be_bytes i)

/-- [libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes::{impl core::ops::function::FnOnce<(core::num::nonzero::NonZero<u64, core::num::niche_types::NonZeroU64Inner>,), libsignal_core::e164::E164> for libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes::closure}::call_once]:
    Source: 'rust/core/src/e164.rs', lines 27:55-27:77 -/
def
  e164.E164.from_be_bytes.closure.Insts.CoreOpsFunctionFnOnceTupleNonZeroU64NonZeroU64InnerE164.call_once
  (c : e164.E164.from_be_bytes.closure)
  (tupled_args : core.num.nonzero.NonZero Std.U64
  core.num.niche_types.NonZeroU64Inner) :
  Result e164.E164
  := do
  ok { inner := tupled_args }

/-- Trait implementation: [libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes::{impl core::ops::function::FnOnce<(core::num::nonzero::NonZero<u64, core::num::niche_types::NonZeroU64Inner>,), libsignal_core::e164::E164> for libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes::closure}]
    Source: 'rust/core/src/e164.rs', lines 27:55-27:77 -/
@[reducible]
def
  e164.E164.from_be_bytes.closure.Insts.CoreOpsFunctionFnOnceTupleNonZeroU64NonZeroU64InnerE164
  : core.ops.function.FnOnce e164.E164.from_be_bytes.closure
  (core.num.nonzero.NonZero Std.U64 core.num.niche_types.NonZeroU64Inner)
  e164.E164 := {
  call_once :=
    e164.E164.from_be_bytes.closure.Insts.CoreOpsFunctionFnOnceTupleNonZeroU64NonZeroU64InnerE164.call_once
}

/-- [libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes]:
    Source: 'rust/core/src/e164.rs', lines 26:4-28:5
    Visibility: public -/
def e164.E164.from_be_bytes
  (bytes : Array Std.U8 8#usize) : Result (Option e164.E164) := do
  let i ← lift (core.num.U64.from_be_bytes bytes)
  let o ←
    core.num.nonzero.NonZero.new
      U64.Insts.CoreNumNonzeroZeroablePrimitiveNonZeroU64Inner i
  core.option.Option.map
    e164.E164.from_be_bytes.closure.Insts.CoreOpsFunctionFnOnceTupleNonZeroU64NonZeroU64InnerE164
    o ()

/-- [libsignal_core::try_scoped]:
    Source: 'rust/core/src/lib.rs', lines 30:0-32:1
    Visibility: public -/
def try_scoped
  {T : Type} {E : Type} {T2 : Type} (coreopsfunctionFnOnceT2TupleResultInst :
  core.ops.function.FnOnce T2 Unit (core.result.Result T E)) (f : T2) :
  Result (core.result.Result T E)
  := do
  coreopsfunctionFnOnceT2TupleResultInst.call_once f ()

/-- [libsignal_core::version::VERSION]
    Source: 'rust/core/src/version.rs', lines 8:0-8:35
    Visibility: public -/
@[global_simps, irreducible] def version.VERSION : Str := toStr "0.96.0"

end libsignal_core
