-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libsignal_core]: type definitions
import Aeneas
import PQXDH.Aeneas2.Extracted.Core.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.longLine false
set_option linter.style.setOption false
set_option linter.style.whitespace false
set_option linter.style.nameCheck false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace libsignal_core

/-- Trait declaration: [core::num::nonzero::private::Sealed]
    Source: '/rustc/library/core/src/num/nonzero.rs', lines 47:12-47:28
    Name pattern: [core::num::nonzero::private::Sealed]
    Visibility: public -/
@[rust_trait "core::num::nonzero::private::Sealed"]
structure core.num.nonzero.private.Sealed (Self : Type) where

/-- Trait declaration: [core::num::nonzero::ZeroablePrimitive]
    Source: '/rustc/library/core/src/num/nonzero.rs', lines 34:0-34:66
    Name pattern: [core::num::nonzero::ZeroablePrimitive]
    Visibility: public -/
@[rust_trait "core::num::nonzero::ZeroablePrimitive"
  (parentClauses := ["markerCopyInst", "privateSealedInst", "markerCopyInst1"])]
structure core.num.nonzero.ZeroablePrimitive (Self : Type) (Self_NonZeroInner :
  Type) where
  markerCopyInst : core.marker.Copy Self
  privateSealedInst : core.num.nonzero.private.Sealed Self
  markerCopyInst1 : core.marker.Copy Self_NonZeroInner

-- derive_more...TryFromReprError: shared root def in PQXDH.Aeneas2.Extracted.Shared.DeriveMore.

-- rand_core_1.RngCore: shared root def in PQXDH.Aeneas2.Extracted.Shared.RandCore.

-- rand.rng.Rng: shared root def in PQXDH.Aeneas2.Extracted.Shared.Rand.

-- rand_core_1.CryptoRng: shared root def in PQXDH.Aeneas2.Extracted.Shared.RandCore.

/-- [libsignal_core::address::ServiceIdKind]
    Source: 'rust/core/src/address.rs', lines 19:0-24:1
    Visibility: public -/
@[discriminant u8]
inductive address.ServiceIdKind where
| Aci : address.ServiceIdKind
| Pni : address.ServiceIdKind

/-- [libsignal_core::address::SpecificServiceId]
    Source: 'rust/core/src/address.rs', lines 63:0-65:1
    Visibility: public -/
structure address.SpecificServiceId (RAW_KIND : Std.U8) where
  uuid : uuid.Uuid

/-- [libsignal_core::address::ServiceId]
    Source: 'rust/core/src/address.rs', lines 185:0-190:1
    Visibility: public -/
@[discriminant isize]
inductive address.ServiceId where
| Aci : address.SpecificServiceId 0#u8 → address.ServiceId
| Pni : address.SpecificServiceId 1#u8 → address.ServiceId

/-- [libsignal_core::address::DeviceId]
    Source: 'rust/core/src/address.rs', lines 684:0-686:1
    Visibility: public -/
structure address.DeviceId where
  id : core.num.nonzero.NonZero Std.U8 core.num.niche_types.NonZeroU8Inner

/-- [libsignal_core::address::InvalidDeviceId]
    Source: 'rust/core/src/address.rs', lines 691:0-691:27
    Visibility: public -/
@[reducible]
def address.InvalidDeviceId := Unit

/-- [libsignal_core::address::ProtocolAddress]
    Source: 'rust/core/src/address.rs', lines 777:0-780:1
    Visibility: public -/
structure address.ProtocolAddress where
  «name» : String
  device_id : address.DeviceId

/-- [libsignal_core::curve::KeyType]
    Source: 'rust/core/src/curve.rs', lines 15:0-17:1
    Visibility: public -/
@[discriminant isize]
inductive curve.KeyType where
| Djb : curve.KeyType

/-- [libsignal_core::curve::CurveError]
    Source: 'rust/core/src/curve.rs', lines 34:0-43:1
    Visibility: public -/
@[discriminant isize]
inductive curve.CurveError where
| NoKeyTypeIdentifier : curve.CurveError
| BadKeyType : Std.U8 → curve.CurveError
| BadKeyLength : curve.KeyType → Std.Usize → curve.CurveError
| InvalidKeyAgreement : curve.CurveError

/-- [libsignal_core::curve::PublicKeyData]
    Source: 'rust/core/src/curve.rs', lines 59:0-61:1 -/
@[discriminant isize]
inductive curve.PublicKeyData where
| DjbPublicKey : Array Std.U8 32#usize → curve.PublicKeyData

/-- [libsignal_core::curve::PublicKey]
    Source: 'rust/core/src/curve.rs', lines 64:0-66:1
    Visibility: public -/
structure curve.PublicKey where
  key : curve.PublicKeyData

/-- [libsignal_core::curve::PrivateKeyData]
    Source: 'rust/core/src/curve.rs', lines 232:0-234:1 -/
@[discriminant isize]
inductive curve.PrivateKeyData where
| DjbPrivateKey : Array Std.U8 32#usize → curve.PrivateKeyData

/-- [libsignal_core::curve::PrivateKey]
    Source: 'rust/core/src/curve.rs', lines 237:0-239:1
    Visibility: public -/
structure curve.PrivateKey where
  key : curve.PrivateKeyData

/-- [libsignal_core::curve::KeyPair]
    Source: 'rust/core/src/curve.rs', lines 321:0-324:1
    Visibility: public -/
structure curve.KeyPair where
  public_key : curve.PublicKey
  private_key : curve.PrivateKey

/-- [libsignal_core::e164::E164]
    Source: 'rust/core/src/e164.rs', lines 13:0-15:1
    Visibility: public -/
structure e164.E164 where
  inner : core.num.nonzero.NonZero Std.U64 core.num.niche_types.NonZeroU64Inner

/-- [libsignal_core::e164::{libsignal_core::e164::E164}::from_be_bytes::closure]
    Source: 'rust/core/src/e164.rs', lines 27:55-27:77 -/
@[reducible]
def e164.E164.from_be_bytes.closure := Unit

end libsignal_core
