-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pqxdh]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace pqxdh

/-- [pqxdh::DH_LEN]
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 50:0-50:25 -/
@[global_simps, irreducible] def DH_LEN : Std.Usize := 32#usize

/-- [pqxdh::put32]: loop body 0:
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 56:4-59:5 -/
@[rust_loop_body]
def put32_loop.body
  (off : Std.Usize) (src : Array Std.U8 32#usize) (out : Slice Std.U8)
  (i : Std.Usize) :
  Result (ControlFlow ((Slice Std.U8) × Std.Usize) (Slice Std.U8))
  := do
  if i < DH_LEN
  then
    let i1 ← Array.index_usize src i
    let i2 ← off + i
    let s ← Slice.update out i2 i1
    let i3 ← i + 1#usize
    ok (cont (s, i3))
  else ok (done out)

/-- [pqxdh::put32]: loop 0:
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 56:4-59:5 -/
@[rust_loop]
def put32_loop
  (out : Slice Std.U8) (off : Std.Usize) (src : Array Std.U8 32#usize)
  (i : Std.Usize) :
  Result (Slice Std.U8)
  := do
  loop
    (fun (out1, i1) => put32_loop.body off src out1 i1)
    (out, i)

/-- [pqxdh::put32]:
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 54:0-60:1 -/
@[reducible]
def put32
  (out : Slice Std.U8) (off : Std.Usize) (src : Array Std.U8 32#usize) :
  Result (Slice Std.U8)
  := do
  put32_loop out off src 0#usize

/-- [pqxdh::pqxdh_secret_input]: loop body 0:
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 81:4-84:5
    Visibility: public -/
@[rust_loop_body]
def pqxdh_secret_input_loop.body
  (out : Array Std.U8 160#usize) (i : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 160#usize) × Std.Usize) (Array Std.U8
    160#usize))
  := do
  if i < DH_LEN
  then
    let a ← Array.update out i 255#u8
    let i1 ← i + 1#usize
    ok (cont (a, i1))
  else ok (done out)

/-- [pqxdh::pqxdh_secret_input]: loop 0:
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 81:4-84:5
    Visibility: public -/
@[rust_loop]
def pqxdh_secret_input_loop
  (out : Array Std.U8 160#usize) (i : Std.Usize) :
  Result (Array Std.U8 160#usize)
  := do
  loop
    (fun (out1, i1) => pqxdh_secret_input_loop.body out1 i1)
    (out, i)

/-- [pqxdh::pqxdh_secret_input]:
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 73:0-90:1
    Visibility: public -/
def pqxdh_secret_input
  (dh1 : Array Std.U8 32#usize) (dh2 : Array Std.U8 32#usize)
  (dh3 : Array Std.U8 32#usize) (ss : Array Std.U8 32#usize) :
  Result (Array Std.U8 160#usize)
  := do
  let out := Array.repeat 160#usize 0#u8
  let out1 ← pqxdh_secret_input_loop out 0#usize
  let (s, to_slice_mut_back) ← lift (Array.to_slice_mut out1)
  let s1 ← put32 s 32#usize dh1
  let out2 := to_slice_mut_back s1
  let (s2, to_slice_mut_back1) ← lift (Array.to_slice_mut out2)
  let s3 ← put32 s2 64#usize dh2
  let out3 := to_slice_mut_back1 s3
  let (s4, to_slice_mut_back2) ← lift (Array.to_slice_mut out3)
  let s5 ← put32 s4 96#usize dh3
  let out4 := to_slice_mut_back2 s5
  let (s6, to_slice_mut_back3) ← lift (Array.to_slice_mut out4)
  let s7 ← put32 s6 128#usize ss
  ok (to_slice_mut_back3 s7)

/-- [pqxdh::pqxdh_secret_input_with_opk]: loop body 0:
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 110:4-113:5
    Visibility: public -/
@[rust_loop_body]
def pqxdh_secret_input_with_opk_loop.body
  (out : Array Std.U8 192#usize) (i : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 192#usize) × Std.Usize) (Array Std.U8
    192#usize))
  := do
  if i < DH_LEN
  then
    let a ← Array.update out i 255#u8
    let i1 ← i + 1#usize
    ok (cont (a, i1))
  else ok (done out)

/-- [pqxdh::pqxdh_secret_input_with_opk]: loop 0:
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 110:4-113:5
    Visibility: public -/
@[rust_loop]
def pqxdh_secret_input_with_opk_loop
  (out : Array Std.U8 192#usize) (i : Std.Usize) :
  Result (Array Std.U8 192#usize)
  := do
  loop
    (fun (out1, i1) => pqxdh_secret_input_with_opk_loop.body out1 i1)
    (out, i)

/-- [pqxdh::pqxdh_secret_input_with_opk]:
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 101:0-120:1
    Visibility: public -/
def pqxdh_secret_input_with_opk
  (dh1 : Array Std.U8 32#usize) (dh2 : Array Std.U8 32#usize)
  (dh3 : Array Std.U8 32#usize) (dh4 : Array Std.U8 32#usize)
  (ss : Array Std.U8 32#usize) :
  Result (Array Std.U8 192#usize)
  := do
  let out := Array.repeat 192#usize 0#u8
  let out1 ← pqxdh_secret_input_with_opk_loop out 0#usize
  let (s, to_slice_mut_back) ← lift (Array.to_slice_mut out1)
  let s1 ← put32 s 32#usize dh1
  let out2 := to_slice_mut_back s1
  let (s2, to_slice_mut_back1) ← lift (Array.to_slice_mut out2)
  let s3 ← put32 s2 64#usize dh2
  let out3 := to_slice_mut_back1 s3
  let (s4, to_slice_mut_back2) ← lift (Array.to_slice_mut out3)
  let s5 ← put32 s4 96#usize dh3
  let out4 := to_slice_mut_back2 s5
  let (s6, to_slice_mut_back3) ← lift (Array.to_slice_mut out4)
  let s7 ← put32 s6 128#usize dh4
  let out5 := to_slice_mut_back3 s7
  let (s8, to_slice_mut_back4) ← lift (Array.to_slice_mut out5)
  let s9 ← put32 s8 160#usize ss
  ok (to_slice_mut_back4 s9)

/-- [pqxdh::derive_split]: loop body 0:
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 139:4-144:5
    Visibility: public -/
@[rust_loop_body]
def derive_split_loop.body
  (okm : Array Std.U8 96#usize) (root_key : Array Std.U8 32#usize)
  (chain_key : Array Std.U8 32#usize) (pqr_key : Array Std.U8 32#usize)
  (i : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 32#usize) × (Array Std.U8 32#usize) ×
    (Array Std.U8 32#usize) × Std.Usize) ((Array Std.U8 32#usize) × (Array
    Std.U8 32#usize) × (Array Std.U8 32#usize)))
  := do
  if i < 32#usize
  then
    let i1 ← Array.index_usize okm i
    let a ← Array.update root_key i i1
    let i2 ← 32#usize + i
    let i3 ← Array.index_usize okm i2
    let a1 ← Array.update chain_key i i3
    let i4 ← 64#usize + i
    let i5 ← Array.index_usize okm i4
    let a2 ← Array.update pqr_key i i5
    let i6 ← i + 1#usize
    ok (cont (a, a1, a2, i6))
  else ok (done (root_key, chain_key, pqr_key))

/-- [pqxdh::derive_split]: loop 0:
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 139:4-144:5
    Visibility: public -/
@[rust_loop]
def derive_split_loop
  (okm : Array Std.U8 96#usize) (root_key : Array Std.U8 32#usize)
  (chain_key : Array Std.U8 32#usize) (pqr_key : Array Std.U8 32#usize)
  (i : Std.Usize) :
  Result ((Array Std.U8 32#usize) × (Array Std.U8 32#usize) × (Array Std.U8
    32#usize))
  := do
  loop
    (fun (root_key1, chain_key1, pqr_key1, i1) => derive_split_loop.body okm
      root_key1 chain_key1 pqr_key1 i1)
    (root_key, chain_key, pqr_key, i)

/-- [pqxdh::derive_split]:
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 134:0-146:1
    Visibility: public -/
def derive_split
  (okm : Array Std.U8 96#usize) :
  Result ((Array Std.U8 32#usize) × (Array Std.U8 32#usize) × (Array Std.U8
    32#usize))
  := do
  let root_key := Array.repeat 32#usize 0#u8
  let chain_key := Array.repeat 32#usize 0#u8
  let pqr_key := Array.repeat 32#usize 0#u8
  derive_split_loop okm root_key chain_key pqr_key 0#usize

/-- [pqxdh::KEY_TYPE_DJB]
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 151:0-151:30 -/
@[global_simps, irreducible] def KEY_TYPE_DJB : Std.U8 := 5#u8

/-- [pqxdh::encode_ec]: loop body 0:
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 167:4-170:5
    Visibility: public -/
@[rust_loop_body]
def encode_ec_loop.body
  (key : Array Std.U8 32#usize) (out : Array Std.U8 33#usize) (i : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 33#usize) × Std.Usize) (Array Std.U8
    33#usize))
  := do
  if i < 32#usize
  then
    let i1 ← Array.index_usize key i
    let i2 ← 1#usize + i
    let a ← Array.update out i2 i1
    let i3 ← i + 1#usize
    ok (cont (a, i3))
  else ok (done out)

/-- [pqxdh::encode_ec]: loop 0:
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 167:4-170:5
    Visibility: public -/
@[rust_loop]
def encode_ec_loop
  (key : Array Std.U8 32#usize) (out : Array Std.U8 33#usize) (i : Std.Usize) :
  Result (Array Std.U8 33#usize)
  := do
  loop
    (fun (out1, i1) => encode_ec_loop.body key out1 i1)
    (out, i)

/-- [pqxdh::encode_ec]:
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 163:0-172:1
    Visibility: public -/
def encode_ec
  (key : Array Std.U8 32#usize) : Result (Array Std.U8 33#usize) := do
  let out := Array.repeat 33#usize 0#u8
  let a ← Array.update out 0#usize KEY_TYPE_DJB
  encode_ec_loop key a 0#usize

/-- [pqxdh::decode_ec]: loop body 0:
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 194:4-197:5
    Visibility: public -/
@[rust_loop_body]
def decode_ec_loop.body
  (bytes : Array Std.U8 33#usize) (key : Array Std.U8 32#usize) (i : Std.Usize)
  :
  Result (ControlFlow ((Array Std.U8 32#usize) × Std.Usize) (Array Std.U8
    32#usize))
  := do
  if i < 32#usize
  then
    let i1 ← 1#usize + i
    let i2 ← Array.index_usize bytes i1
    let a ← Array.update key i i2
    let i3 ← i + 1#usize
    ok (cont (a, i3))
  else ok (done key)

/-- [pqxdh::decode_ec]: loop 0:
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 194:4-197:5
    Visibility: public -/
@[rust_loop]
def decode_ec_loop
  (bytes : Array Std.U8 33#usize) (key : Array Std.U8 32#usize) (i : Std.Usize)
  :
  Result (Array Std.U8 32#usize)
  := do
  loop
    (fun (key1, i1) => decode_ec_loop.body bytes key1 i1)
    (key, i)

/-- [pqxdh::decode_ec]:
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 188:0-199:1
    Visibility: public -/
def decode_ec
  (bytes : Array Std.U8 33#usize) :
  Result (Option (Array Std.U8 32#usize))
  := do
  let i ← Array.index_usize bytes 0#usize
  if i != KEY_TYPE_DJB
  then ok none
  else
    let key := Array.repeat 32#usize 0#u8
    let key1 ← decode_ec_loop bytes key 0#usize
    ok (some key1)

/-- [pqxdh::associated_data]: loop body 0:
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 221:4-225:5
    Visibility: public -/
@[rust_loop_body]
def associated_data_loop.body
  (a : Array Std.U8 33#usize) (b : Array Std.U8 33#usize)
  (out : Array Std.U8 66#usize) (i : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 66#usize) × Std.Usize) (Array Std.U8
    66#usize))
  := do
  if i < 33#usize
  then
    let i1 ← Array.index_usize a i
    let out1 ← Array.update out i i1
    let i2 ← Array.index_usize b i
    let i3 ← 33#usize + i
    let a1 ← Array.update out1 i3 i2
    let i4 ← i + 1#usize
    ok (cont (a1, i4))
  else ok (done out)

/-- [pqxdh::associated_data]: loop 0:
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 221:4-225:5
    Visibility: public -/
@[rust_loop]
def associated_data_loop
  (a : Array Std.U8 33#usize) (b : Array Std.U8 33#usize)
  (out : Array Std.U8 66#usize) (i : Std.Usize) :
  Result (Array Std.U8 66#usize)
  := do
  loop
    (fun (out1, i1) => associated_data_loop.body a b out1 i1)
    (out, i)

/-- [pqxdh::associated_data]:
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 216:0-227:1
    Visibility: public -/
def associated_data
  (ika : Array Std.U8 32#usize) (ikb : Array Std.U8 32#usize) :
  Result (Array Std.U8 66#usize)
  := do
  let a ← encode_ec ika
  let b ← encode_ec ikb
  let out := Array.repeat 66#usize 0#u8
  associated_data_loop a b out 0#usize

/-- [pqxdh::x25519_agree]:
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 244:0-246:1 -/
axiom x25519_agree
  :
  Array Std.U8 32#usize → Array Std.U8 32#usize → Result (Array Std.U8
    32#usize)

/-- [pqxdh::mlkem_encapsulate]:
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 254:0-256:1 -/
axiom mlkem_encapsulate
  :
  Array Std.U8 1568#usize → Array Std.U8 32#usize → Result ((Array Std.U8
    32#usize) × (Array Std.U8 1569#usize))

/-- [pqxdh::mlkem_decapsulate]:
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 266:0-268:1 -/
axiom mlkem_decapsulate
  :
  Array Std.U8 3168#usize → Array Std.U8 1569#usize → Result (Array Std.U8
    32#usize)

/-- [pqxdh::hkdf_sha256_derive]:
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 276:0-278:1 -/
axiom hkdf_sha256_derive
  : Slice Std.U8 → Slice Std.U8 → Result (Array Std.U8 96#usize)

/-- [pqxdh::ec_is_canonical]:
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 283:0-285:1 -/
axiom ec_is_canonical : Array Std.U8 32#usize → Result Bool

/-- [pqxdh::PQXDH_LABEL]
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 288:0-288:81 -/
@[global_simps, irreducible]
def PQXDH_LABEL : Array Std.U8 46#usize :=
  Array.make 46#usize [
    87#u8, 104#u8, 105#u8, 115#u8, 112#u8, 101#u8, 114#u8, 84#u8, 101#u8,
    120#u8, 116#u8, 95#u8, 88#u8, 50#u8, 53#u8, 53#u8, 49#u8, 57#u8, 95#u8,
    83#u8, 72#u8, 65#u8, 45#u8, 50#u8, 53#u8, 54#u8, 95#u8, 67#u8, 82#u8,
    89#u8, 83#u8, 84#u8, 65#u8, 76#u8, 83#u8, 45#u8, 75#u8, 89#u8, 66#u8,
    69#u8, 82#u8, 45#u8, 49#u8, 48#u8, 50#u8, 52#u8
    ]

/-- [pqxdh::KeyPair]
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 294:0-297:1
    Visibility: public -/
structure KeyPair where
  private_key : Array Std.U8 32#usize
  public_key : Array Std.U8 32#usize

/-- [pqxdh::HandshakeKeys]
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 301:0-305:1
    Visibility: public -/
structure HandshakeKeys where
  root_key : Array Std.U8 32#usize
  chain_key : Array Std.U8 32#usize
  pqr_key : Array Std.U8 32#usize

/-- [pqxdh::InitiatorAgreement]
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 309:0-312:1
    Visibility: public -/
structure InitiatorAgreement where
  keys : HandshakeKeys
  kyber_ciphertext : Array Std.U8 1569#usize

/-- [pqxdh::InitiatorParameters]
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 318:0-325:1
    Visibility: public -/
structure InitiatorParameters where
  our_identity_key_pair : KeyPair
  our_ephemeral_key_pair : KeyPair
  their_identity_key : Array Std.U8 32#usize
  their_signed_pre_key : Array Std.U8 32#usize
  their_one_time_pre_key : Option (Array Std.U8 32#usize)
  their_kyber_pre_key : Array Std.U8 1568#usize

/-- [pqxdh::RecipientParameters]
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 330:0-338:1
    Visibility: public -/
structure RecipientParameters where
  our_identity_key_pair : KeyPair
  our_signed_pre_key_pair : KeyPair
  our_one_time_pre_key_pair : Option KeyPair
  our_kyber_secret_key : Array Std.U8 3168#usize
  their_identity_key : Array Std.U8 32#usize
  their_ephemeral_key : Array Std.U8 32#usize
  their_kyber_ciphertext : Array Std.U8 1569#usize

/-- [pqxdh::pqxdh_initiate]:
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 356:0-381:1
    Visibility: public -/
def pqxdh_initiate
  (params : InitiatorParameters) (coins : Array Std.U8 32#usize) :
  Result InitiatorAgreement
  := do
  let dh1 ←
    x25519_agree params.our_identity_key_pair.private_key
      params.their_signed_pre_key
  let dh2 ←
    x25519_agree params.our_ephemeral_key_pair.private_key
      params.their_identity_key
  let dh3 ←
    x25519_agree params.our_ephemeral_key_pair.private_key
      params.their_signed_pre_key
  let (ss, ct) ← mlkem_encapsulate params.their_kyber_pre_key coins
  let okm ←
    match params.their_one_time_pre_key with
    | none =>
      do
      let secret_input ← pqxdh_secret_input dh1 dh2 dh3 ss
      let s ← lift (Array.to_slice secret_input)
      let s1 ← lift (Array.to_slice PQXDH_LABEL)
      hkdf_sha256_derive s s1
    | some opk =>
      do
      let dh4 ← x25519_agree params.our_ephemeral_key_pair.private_key opk
      let secret_input ← pqxdh_secret_input_with_opk dh1 dh2 dh3 dh4 ss
      let s ← lift (Array.to_slice secret_input)
      let s1 ← lift (Array.to_slice PQXDH_LABEL)
      hkdf_sha256_derive s s1
  let (root_key, chain_key, pqr_key) ← derive_split okm
  ok { keys := { root_key, chain_key, pqr_key }, kyber_ciphertext := ct }

/-- [pqxdh::pqxdh_accept]:
    Source: 'demos/rust/pqxdh/pqxdh.rs', lines 394:0-419:1
    Visibility: public -/
def pqxdh_accept
  (params : RecipientParameters) : Result (Option HandshakeKeys) := do
  let b ← ec_is_canonical params.their_ephemeral_key
  if b
  then
    let dh1 ←
      x25519_agree params.our_signed_pre_key_pair.private_key
        params.their_identity_key
    let dh2 ←
      x25519_agree params.our_identity_key_pair.private_key
        params.their_ephemeral_key
    let dh3 ←
      x25519_agree params.our_signed_pre_key_pair.private_key
        params.their_ephemeral_key
    let ss ←
      mlkem_decapsulate params.our_kyber_secret_key
        params.their_kyber_ciphertext
    let okm ←
      match params.our_one_time_pre_key_pair with
      | none =>
        do
        let secret_input ← pqxdh_secret_input dh1 dh2 dh3 ss
        let s ← lift (Array.to_slice secret_input)
        let s1 ← lift (Array.to_slice PQXDH_LABEL)
        hkdf_sha256_derive s s1
      | some opk_pair =>
        do
        let dh4 ←
          x25519_agree opk_pair.private_key params.their_ephemeral_key
        let secret_input ← pqxdh_secret_input_with_opk dh1 dh2 dh3 dh4 ss
        let s ← lift (Array.to_slice secret_input)
        let s1 ← lift (Array.to_slice PQXDH_LABEL)
        hkdf_sha256_derive s s1
    let (root_key, chain_key, pqr_key) ← derive_split okm
    ok (some { root_key, chain_key, pqr_key })
  else ok none

end pqxdh
